postgres_password: ENC[AES256_GCM,data:kGZFfU3HHP6+Ub0el0/9/MHOvTiycyPYr64jWF8IjcQuFoFs6R3p3eNC5+5tV5Vy,iv:zKx90WDQ6PlKMHNUMAH/G+DIH/MssQ5BIq07flGzjzI=,tag:j3qROTp1qM04jKmTvLSqCw==,type:str]
redis_password: ENC[AES256_GCM,data:tzVvhnasY+eGrFQJzWIO0+2pfa4F/g5mVV9LbTZFB+nIN5faRbPdHNIyYx4I3mJV,iv:389tXrPuLYHb1Uia1pV7zZiuMfkhv/r7gJieCT+DKJY=,tag:TEIbSCcAS674gqoRCFHL8Q==,type:str]
jwt_secret: ENC[AES256_GCM,data:YGfarQEB3c4alyFovyuBSwAl9Kd11HNshdCjhWrF9EUsM6Ply0b6vuSC1bAjgc4MTH5GoPjC1PKwyf4PeqgN8g==,iv:iZbrAjbXc/X67JjR2317RgLDzG7P6VA9dmUEDO5liO0=,tag:o1SBshjIesvYKi1NW2+mbw==,type:str]
refresh_token_secret: ENC[AES256_GCM,data:JqujD5nVla36P8KChzT/SA12yqi5QnB+CgYLCfzrEuMBkUkCm0+/eW0LzmFkbsbXW8Pg32xtxvGBPAe/6b8LNg==,iv:o3YZ6O8rmF6Ba9SIPm6vUi+ZElVO1a0SixOMf9vCuYw=,tag:9/h7xwg4SeJnQPzjFjDARA==,type:str]
captcha_secret: ENC[AES256_GCM,data:vMPIF/lSJqm957dHvFG52ob8CELkVmHm6YE21wLCLxPSBnucrJMje6uB1lORsrM1CNxdwe3Xem3VZlwGeNQ8ig==,iv:PAn/kuJ2Dr92yYzVbdEX3netywUO0A0dUF/2sHyrYjM=,tag:rjNbwqLxhUyRhM3a3P4Vaw==,type:str]
reaper_password: ENC[AES256_GCM,data:SwsNCK8iGNW0tiplqW85TkPT8Sq8KEAZJPOwpydmAv0ZsfOYQ/jFjlxN2hkBZ6Ta,iv:BKB/o+UeU2prATqpsNF271yNmX1fhPqr/ngSA33M5I4=,tag:/J0rq5EH9MnCAXNtI8RBqA==,type:str]
grafana_admin_password: ENC[AES256_GCM,data:AdC3A9lZwfZ41dubaYgxfE5IUtDk+603WuGRVGaJBuQ=,iv:MmCoxqBdz8TyGPsEFx4K7BRmyKsMp45CzfbvekYlUtw=,tag:q3mUmuYkB7n5QU5JybJQ8w==,type:str]
smtp_password: ENC[AES256_GCM,data:Up5UFs3zaD4Czonqj2EGTSEXNERO0CZpqbwW0iENJ0E=,iv:eq9f41pbs2uBCUI/4rE1ZTeoQPC+26lwyEeZHoX3lcY=,tag:vPD6GBSLgxH/bwAS/RzDAQ==,type:str]
email_verify_secret: ENC[AES256_GCM,data:zibxfBTO38GcVXhspaJnwAVLKwHRJFYV9Kbs3LskqxU9vtcJmEEZLGXM4trjblFFdy7JOT7eDb8/jt+iakCwHg==,iv:fIJcavKzLNhmL99sdCM1/5bIz2kzQ1SRSnxR3SUoySw=,tag:gVy/9XKlok+R80vLVqfIBQ==,type:str]
alert_webhook_url: ENC[AES256_GCM,data:3ttHhmVTuErjQva8g1AFu+9Ec5hVjnz8o52oRfbhSViP8+bwyTqZPDvGYwKo9TwV0Vmb,iv:vTGS7ncSLL1gYdxY7oH8SE4t1gKvxF3IKekKJI5Rufs=,tag:eY1/bxqWaGsihV5WonW9og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MEcxQ2FmOEN6L1lZaCtz
            MEU0UmVkSUUwZDJibi94VkVBVjhBRUljSGtjCkg0anFkUDdwRVZkYStnM2xETHBL
            QXByWmx0UzFSWlRmSlNLeFVxZGVzRHMKLS0tIEZNUEUvVExrZUpQUFdkTFhOOVRF
            MlJwL2hIUUVJUUtXa3J6U0Q1YXdkYnMKG7rW5ExEKqx/UN7MGgZFWQSA/tEZ7iJI
            JBcbmKNRaEBO0vqLZpCpy9iAhTbYMRX6yJngZ/Lvk+p7B9UaVn/Lxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h86rpwqkfcqptwldqulg6wekvldzek0h44fvm5u6msexmdc3q5ts7mp46f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaVdOdXlaQWUvV3o3M2JV
            RkZpMkZOUmJXdC9Md3Z6ZlVDbnNVWUtEa0VnClJvc0M2Z1I2ekM3dGsrVjQwaVho
            b250WVAvN2VmZjEvclhkR2x1aGZMOFkKLS0tIHQzS2NqTFZHa2dSVkpnSXU3U3hN
            emgweXRRM1dRQitZYjdYaDZ3VFFydHcKULV29g/900dLcmRIl6ujLP6EXyiiNXVa
            Fq5TCye7FVp/yEVm9fmVfx+0lwE2/lXFI2a4dr6s6weUQIG+5CLwCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wdnafv7jd7r0l7wvtl9lz60yu27shw4nay0fhugnad8tetfwh5pqs9z00u
    lastmodified: "2026-08-04T11:18:06Z"
    mac: ENC[AES256_GCM,data:8WMwd0LMr0BJ04+9thRJhS9FqLpovD1tK1L21z2xYgWZEGsFYGqm8bsi3bkWMKr9W/RrA8IWMfDb/b+9TZFdM5XTMq4RchX4bco+AWAFYoOYwCxdChZjwvA3AI7oUzmYLyUVMEejAk7yEpNW+pPTopC/txodHNiCEmUOCO5zGmg=,iv:Wri9Fg/VGp040MQw4VHJ6Gg2dYTLP5xTLQ6mpv85O5U=,tag:r7XkL0BCIqB7IPYzWmTArg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
