#!/usr/bin/env python3
"""tools/fork-delta-lint.py — 機器式驗 base-web fork-delta「原行」紀律（constitution §III L114）。

最原始源-基線＝`fork260509-soybean-admin-base/` @ `example` 分支 tip（實體目錄、須先切到）。
判定：base-web 若改動 example 既有 inline 行（該行不再逐字存在於我方版）→ 我方檔內**必須**有
`// [rev5-inline …] 原行: <example 那行原始內容>` 標記、且 `原行:` 後內容＝基線該行（正規化後相等）。
缺 → 紅、指名「檔:上游原行」。我方新檔／純新增行（example 沒有）不要求原行。

★補位（rev4:B-052）：新增型（基線沒有的新行）雖不要原行，但依 §III 須走「新增型圈界」rev5-inline
標記——`find_unmarked_additions` 補這道，令「所有 fork-delta（修改＋新增）皆帶 rev5-inline 標記、
上游 rebase 可定位」。機器生成檔（Generated by header）由重算保證 fork-delta、豁免手標。

每次執行**先跑 self-test**（合成缺原行/缺圈界樣本、證 lint 真能攔——防 vacuous 恆綠），再跑實掃。
"""
import difflib
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASEWEB = os.path.join(REPO, "base-web")
FORK = os.path.join(REPO, "fork260509-soybean-admin-base")
BASELINE = "example"
CONSTITUTION = os.path.join(REPO, ".specify", "memory", "constitution.md")

MARKER = re.compile(r"原行:\s*(.*\S)\s*$")

# 軌道名抽取（T069②；B-058 實測五種標記形都要吃）：捕 `[rev5-inline` 後首個大寫 token。
# 字元類止於 `(`（用途後綴 (a)/(i)…）、`+`（新增型尾綴）、空白（刀號）與 `]`——即抽出的
# 恆為「剝掉用途後綴與尾綴 + 之後」的裸名，恰是 §III.2 名冊列的形（B-058：不剝就會把
# 合法標記整批誤判為名冊外）。五形＝`NAME+ 刀號`／`NAME(a) 刀號`／`NAME(i)`（無刀號）／
# `NAME 刀號`（.env 裸形、掃描面外但抽取器仍容忍）／名冊側 `**`／`★` 裝飾（由 load_roster 剝）。
TRACK = re.compile(r"\[rev5-inline\s+([A-Z][A-Z0-9-]*)")


def die(msg):
    print(f"[fork-delta-lint] ✗ {msg}", file=sys.stderr)
    sys.exit(2)


def load_roster():
    """T069①：授權軌道名冊＝constitution §III.2 ★軌道 ∪ §III.1 三軌道。

    掃描錨（§III.2 自述）：表格資料列以 `|` 起、跳標題列與分隔列；軌道名於首欄、
    剝 `**` 與 `★` 裝飾。★檔缺席／掃空＝die（fail-loud，絕不默認空名冊放行一切）。
    T069⑤ 三重非 vacuous 斷言亦在此落地（每次執行都跑）：①名冊整體非空
    ②§III.2 ★段貢獻列數 ≥ 4 ③承襲指針散文中本刀不開的兩名（MODAL-WIRING／
    BASE-WEB-DEVPROXY-WIRING）不得被掃進名冊——證掃描面只及表格、不及散文。"""
    if not os.path.isfile(CONSTITUTION):
        die(f"constitution 不存在：{CONSTITUTION}（T069 名冊來源、缺之即無授權判準）")
    roster, s1_rows, s2_rows, section = set(), 0, 0, None
    for line in open(CONSTITUTION, encoding="utf-8").read().splitlines():
        if line.startswith("### III.1"):
            section = 1
            continue
        if line.startswith("### III.2"):
            section = 2
            continue
        if line.startswith(("## ", "### ")):
            section = None
            continue
        if section is None or not line.startswith("|"):
            continue
        cells = line.split("|")
        name = cells[1].strip().strip("*★").strip() if len(cells) > 1 else ""
        # 跳標題列（首欄「軌道」）與分隔列（純 -/: 字元）
        if not name or name == "軌道" or set(name) <= set("-: "):
            continue
        roster.add(name)
        if section == 1:
            s1_rows += 1
        elif section == 2:
            s2_rows += 1
    if not roster:
        die("名冊掃描為空——constitution §III.1/§III.2 表格錨可能被改動（T069⑤ 非空斷言①）")
    if s2_rows < 4:
        die(f"§III.2 ★軌道表僅掃得 {s2_rows} 列（須 ≥4）——表錨或列形被改動（T069⑤ 非空斷言②）")
    # ★§III.1 半邊的同形斷言（final holistic review 補：原三重斷言**全部只約束 §III.2**，
    #   §III.1 三軌道可靜默自名冊掉線而 lint 全綠）。實測失效鏈：把 `### III.1` 改成
    #   `### III-1`（或整表刪除）⇒ roster 由 7 名縮成 4 名、輸出仍宣稱「軌道名皆在名冊」，
    #   直到某刀第一次用 BASE-WEB-ADAPT／BASE-WEB-WRAPPER 開**修改型**標記才報「不在名冊、
    #   須先走 §V.2 Amendment」——指向錯誤修法（該軌道早已授權），真病灶不被指出。
    #   與 .githooks/pre-commit 補 constitution 觸發源所修的是同一個「fail-late 且誤導」病。
    if s1_rows != 3:
        die(f"§III.1 預設可動軌道表掃得 {s1_rows} 列（須恰 3）——表錨或列形被改動；名冊會靜默少收三名而全鏈照綠（T069⑤ 非空斷言③）")
    for absent in ("MODAL-WIRING", "BASE-WEB-DEVPROXY-WIRING"):
        if absent in roster:
            die(f"{absent} 被掃進名冊——它只存在於承襲指針散文（§III.2 表外宣告 2、本刀未開），"
                f"掃描面誤及散文＝名冊失真（T069⑤ 反例斷言）")
    return roster


def find_rogue_tracks(ours_content, roster):
    """T069③：修改型標記（同行含 `原行:`）的軌道名 ∈ 授權名冊斷言＋「同行必含
    `[rev5-inline` token」強制（堵現行漏洞：任何含 `原行:` 的行都算已記錄）。
    回 ([(標記行去空白, 錯因)], 已檢查之修改型標記行數)。★射程僅修改型——新增型
    `NAME+` 不入名冊（§III.2 表外宣告 3、承 ADR 0021 款 1）。"""
    out, checked = [], 0
    for l in ours_content.splitlines():
        if "原行:" not in l:
            continue
        s = l.strip()
        if "[rev5-inline" not in s:
            out.append((s, "缺 [rev5-inline token——裸 `原行:` 不構成合法修改型標記"))
            continue
        checked += 1
        m = TRACK.search(s)
        if not m:
            out.append((s, "抽不出軌道名（標記形制不符 `[rev5-inline <TRACK>…]`）"))
        elif m.group(1) not in roster:
            out.append((s, f"軌道名 {m.group(1)} 不在授權名冊（constitution §III.1/§III.2）"))
    return out, checked


def sh(args, cwd):
    # 清掉 GIT_* env：git hook 會把外層 repo 的 GIT_DIR/GIT_INDEX_FILE 洩漏給子行程，
    # 害對 base-web worktree（.git 為檔）跑 git 抓錯 index（.git/index: Not a directory）。
    env = {k: v for k, v in os.environ.items() if not k.startswith("GIT_")}
    return subprocess.run(args, cwd=cwd, capture_output=True, text=True, env=env)


def is_code(line):
    s = line.strip()
    return bool(s) and not s.startswith(("//", "/*", "*", "<!--"))


def norm(line):
    # 去尾端逗號/分號：加新同層條目使前一行多尾逗號，屬新增型副作用、非語意改變（§III「語意被改變」才算修改型）
    return line.strip().rstrip(",;").rstrip()


def find_missing(base_content, ours_content):
    """回傳「基線有、我方既無此行、又無對應原行標記」的上游**原行**（供逐字補回）。
    ★比對用 norm（去尾標點）、輸出保原行原貌（含尾逗號等）。"""
    ours = ours_content.splitlines()
    ours_lines = {norm(l) for l in ours}
    recorded = set()
    for l in ours:
        if "[rev5-inline" not in l:
            continue  # T069③：裸 `原行:`（無 rev5-inline token）不算已記錄——防形制外洗白
        m = MARKER.search(l)
        if m:
            recorded.add(norm(m.group(1)))
    seen = set()
    missing = []
    for raw in base_content.splitlines():
        if not is_code(raw):
            continue
        n = norm(raw)
        if not n or n in ours_lines or n in recorded or n in seen:
            continue
        seen.add(n)
        missing.append(raw.strip())  # 原行原貌（去首尾空白、保尾逗號）
    return missing


def is_generated(content):
    """檔頭 8 行含生成器標記＝機器生成檔（elegant-router／unplugin 等）：fork-delta 由重算保證、
    不手標圈界，故豁免。★限檔頭（避免誤中 hand-written 檔散文裡的『auto generated』字樣——
    如 store/modules/route/index.ts 第 36 行、theme/shared.ts 第 264 行）。"""
    head = "\n".join(content.splitlines()[:8])
    return bool(re.search(r"Generated by|@generated", head))


def _code_of_line(line, closing):
    """單行去註解：回（碼文本, 新 closing 態）。`closing`＝跨行區塊註解的待閉合 token
    （None＝不在註解內）。★逐字元掃描、正確處理跨行 /* */、<!-- --> 之開閉——含『同行
    閉合後緊接碼』（對抗驗證 NF-A：`*/ code` 不再整行丟棄）與『同行連續 /* */ /* …』
    （對抗驗證 NF-C：第二註解 body 不洩為碼）；行註解 // 到行尾（不跨行、closing 不置位）。
    [`_block_code_added`]（新增型圈界掃描）與 [`strip_comments`]（B-061/B-062 語意掃描）
    共用這一份——去註解規則只此一處，兩面不分岔。"""
    rest, code = line, ""
    while rest:
        if closing:                          # 在跨行區塊註解內、找閉合
            k = rest.find(closing)
            if k < 0:
                return code, closing
            rest, closing = rest[k + len(closing):], None
            continue
        cands = [(rest.find(t), t) for t in ("//", "/*", "<!--") if t in rest]
        if not cands:
            return code + rest, None
        i, t = min(cands)
        code += rest[:i]
        if t == "//":
            return code, None                # 行註解到行尾
        closing, rest = ("*/" if t == "/*" else "-->"), rest[i + len(t):]
    return code, closing


def _block_code_added(added):
    """回 added 各『去註解後仍有實質碼』的行（原行原貌）。去註解規則見 [`_code_of_line`]。"""
    out, closing = [], None
    for l in added:
        code, closing = _code_of_line(l, closing)
        if code.strip():
            out.append(l)
    return out


def strip_comments(content):
    """全檔去（跨行）註解後的碼文本（行結構保留、行數不變——命中行可回指原貌）。
    B-061／B-062 的語意掃描面：那幾支檔的 `原行:` 註解裡就有被禁字面，不剝註解即恆紅。"""
    out, closing = [], None
    for l in content.splitlines():
        code, closing = _code_of_line(l, closing)
        out.append(code)
    return "\n".join(out)


def strip_ends_open(content):
    """去註解掃到 EOF 時是否**仍卡在**跨行區塊註解內（`closing` 未歸零）。
    真 .ts／.vue 不可能以未閉合 `/*`／`<!--` 收尾（語法錯、build 當場紅），故此態的唯一
    現實成因＝[`_code_of_line`] **不解析字串常值**：`/*` 或 `<!--` 出現在字串字面裡即置位
    `closing`、把其後全部內容當註解吞掉。那正是 B-061 語意守的恆綠路徑（掃描零命中→rc=0），
    且與「upstream rebase 解錯把 toast 插回來」可在同一次 rebase 同時發生。"""
    closing = None
    for l in content.splitlines():
        _, closing = _code_of_line(l, closing)
    return closing is not None


def _structural_only(line):
    """純結構標點行（}、);、],… 無任何識別碼字元）＝區塊延續、不需獨立圈界（避免對閉合括號誤報）。"""
    return not re.search(r"[0-9A-Za-z_$]", line)


def _block_has_marker(added):
    """change-block 內有無合法 rev5 標記——限『註解行』且含 [rev5-inline（排除字串常值內同名子字串
    的自我認證：對抗驗證 FN2）。"""
    return any(s.startswith(("//", "/*", "*", "<!--")) and "[rev5-inline" in s
               for s in (l.strip() for l in added))


def find_unmarked_additions(base_content, ours_content):
    """回「新增碼 change-block 卻無合法 rev5-inline 標記」之首個實質新增行（供補圈界標記）。★補位
    find_missing（後者驗修改型缺原行）；本函式驗新增型缺圈界，合起來令所有 fork-delta 皆帶標記。
    §III 新增型圈界紀律。

    以 difflib.unified_diff 取差異、按 **change-block**（連續 +/- 行為一塊、context 行〔含空白〕分界）；
    ★只驗『純新增塊』（塊內無任何被移除碼行）——含被移除碼行者＝修改型/替換區塊、由 find_missing
    驗原行、本函式跳過（故 captcha 型『替換邏輯與其原行標記被空白 context 分隔』不誤報）。純新增塊去
    （跨行）註解＋純結構標點行（閉合 } 等＝區塊延續）後仍有實質新增碼卻無合法標記（限註解行、字串
    常值內子字串不算）→報首行。分工：修改型缺原行→find_missing；純新增（新 import/欄位）缺圈界→本函式。
    ★已知可接受殘留（2 輪對抗驗證後定；見 LESSONS）：①與修改型同塊（無 context 分隔）的額外未圈界
    新增歸該塊原行標記涵蓋、不另報（修它會重引入 captcha 型替換誤報張力）；②字串常值內未閉合 /* 之
    後續行罕見被當註解（窄 FN；不做 string-parsing）。假 DEL 洗白被 find_missing『刪行缺原行』兜住。"""
    out = []
    added, removed = [], []
    seen_hunk = False

    def flush():
        if any(is_code(l) for l in removed):
            return                           # 修改型/替換塊（含移除碼）→ 歸 find_missing、本函式跳過
        substantive = [l for l in _block_code_added(added) if not _structural_only(l)]
        if substantive and not _block_has_marker(added):
            out.append(substantive[0].strip())

    for line in difflib.unified_diff(base_content.splitlines(),
                                     ours_content.splitlines(), n=3, lineterm=""):
        if line.startswith("@@"):
            flush(); added, removed = [], []; seen_hunk = True
        elif not seen_hunk:
            continue                         # unified_diff 檔頭 ---/+++（首個 @@ 前）——seen_hunk 旗標
        elif line.startswith("+"):           # 認檔頭，內容以 ++/-- 起首不撞 +++/---（對抗驗證 INT1）
            added.append(line[1:])
        elif line.startswith("-"):
            removed.append(line[1:])
        else:                                # context 行（含空白）＝ change-block 分界
            flush(); added, removed = [], []
    flush()
    return out


# B-061：假成功 toast 防回歸的守門標的——★逐檔列舉、不可全樹掃：
# `src/views/alova/scenes/modules/captcha-verification.vue` 有同一句但那是 alova demo
# （B-018 去留射程），全樹掃會誤報。此四支＝003-auth-session U-M 消滅假成功 toast 的檔集。
FAKE_TOAST_FILES = (
    "src/views/_builtin/login/modules/code-login.vue",
    "src/views/_builtin/login/modules/register.vue",
    "src/views/_builtin/login/modules/reset-pwd.vue",
    "src/hooks/business/captcha.ts",
)
# `$message` 的 success 呼叫形（`?.` 與 `.` 兩形皆攔；`window.$message?.success(…)`）。
FAKE_TOAST = re.compile(r"\$message\s*(?:\?\.|\.)\s*success")

# B-062：graceful fallback 守門標的（憲法 §III.2 ★BASE-WEB-I18N-WIRING(i) 收窄條件）。
I18N_FALLBACK_FILE = "src/service/request/index.ts"

# ★交付面「必存字面」守（final holistic review 補）：前兩組守的是「不得出現」，
# 本組守的是「必須存在」——upstream rebase 對該 hunk 選了 upstream 版、或有人「清理」該行，
# 五道閘（typecheck／fork-delta-lint／docs-sync／rust 全套／wire-schema）全部照綠，
# 而交付面當場消失。逐檔逐形列舉，每列＝(檔, 必存正則, 違反時的後果說明)。
REQUIRED_LITERALS = (
    ("src/store/modules/route/index.ts",
     re.compile(r"addConstantRoutes\(\s*\[\s*\.\.\.\s*staticRoute\.constantRoutes\s*,"),
     "constant routes MUST 為**併入** static 常量集而非取代（憲法 §III.2 (a)／spec FR-020）；"
     "回退成 upstream 的 `addConstantRoutes(data)` 後，seed constant=TRUE 為 0 列 ⇒ 後端回 [] ⇒ "
     "login／403／404／500／iframe-page 五條 builtin 常量路由被整組清空，**登入頁本身不可達**"),
    ("src/layouts/modules/global-header/components/user-avatar.vue",
     re.compile(r"catch\s*\{"),
     "登出前的 `await fetchLogout(...)` MUST 為 best-effort、**失敗不得阻斷** `resetStore()`"
     "（憲法 §III.2 (i) 逐字收窄）；拿掉錯誤處理後，後端 logout 一失敗就整個卡在對話框、"
     "使用者登不出去"),
)


def find_fake_success_toast(content):
    """B-061：去註解後不得出現 `$message` 的 success 呼叫（U-M 核心交付「假成功 toast」
    防回歸——base-web 無測試 runner、五道閘全看不見這個語意，upstream rebase 解錯即回歸）。
    回 ([去註解後命中行原貌], **未**去註解時的命中數)。★回傳形沿 [`find_bare_t_calls`]：
    「零違規」與「一個都沒看到檔案內容」是兩件事，靠第二欄分辨。四支標的檔現況第二欄
    **恰為 1**（唯一那處字面在 `原行:` 註解裡），呼叫端據此雙向 die：0＝掃描面沒看到檔案
    內容（或標記已消失）、≥2＝多冒出一處被禁字面（toast 被插回來、卻因去註解走偏而沒進
    違規清單——[`strip_ends_open`] 攔的同一病灶之另一半）。
    ★去註解**失效**（退化成 identity）的反方向是恆紅、由 self-test Z3 擋，不需本欄。"""
    raw_lines = content.splitlines()
    # ★第二欄獨立數 raw、不搭 zip：`strip_comments` 的末行若被吃成空字串，join 後尾隨的
    #   `\n` 會被 splitlines 吞掉一行，zip 隨之截短——恰好漏數的就是「被吞在註解態裡的尾段」。
    raw_hits = sum(1 for l in raw_lines if FAKE_TOAST.search(l))
    hits = [raw.strip() for raw, code in zip(raw_lines, strip_comments(content).splitlines())
            if FAKE_TOAST.search(code)]
    return hits, raw_hits


def find_bare_t_calls(content):
    """B-062：`translateBackendMsg` 內每個 `$t(` 呼叫皆須帶 fallback 引數（`$t(key, msg)`
    或 `$t(key, named, msg)`）——退化成 `$t(key)` 時 vue-i18n 對未命中鍵回**查詢鍵本身**、
    畫面顯裸 `backend.*` 鍵（違「未命中 MUST graceful fallback、不得顯裸 key」收窄），而
    typecheck 綠（合法多載）、quickstart 走不到該腿。
    回 ([違規呼叫字面], 已檢查之函式體內 `$t(` 呼叫數)。★回傳形沿 [`find_rogue_tracks`]：
    「零違規」與「一個都沒檢查到」是兩件事，靠 checked 欄分辨——只回清單則守門面整個消失
    （簽名還在但 body 被抽空、或 `$t` 被搬進 helper 而 fallback 在 helper 內被拔掉）時
    照樣回 `[]` 恆綠，與 T069⑤ 對名冊斷言所做的結構性自證同一形（呼叫端 die）。
    ★射程僅該函式體（大括號配平取界）：`translateDetailValue` 的 `$t('backend.common.
    listSeparator')` 單參形合法在案、不得誤傷。
    ★判準＝**末個頂層引數須為該函式首參識別字**（＝後端原文 msg；識別字由簽名現讀、不寫死）。
    兩種退化形一次涵蓋：`$t(key)`（整組拔成單參）與 `$t(key, named)`（三參形只被吃掉末參，
    upstream rebase 解衝突時更像會發生的形）；不需語意推斷第二參是字串還是 named 插值物件。"""
    code = strip_comments(content)
    m = re.search(r"function translateBackendMsg\s*\(\s*([A-Za-z_$][\w$]*)", code)
    if m is None:
        return (["函式 translateBackendMsg（具名首參形）不存在——守門標的結構性缺席"
                 "（同計違規、先查該檔）"], 0)
    fallback = m.group(1)
    # 函式體＝自簽名後首個 { 起、大括號配平（跳過字串常值）到閉合
    i = code.index("{", m.end())
    depth, quote, j = 0, None, i
    while j < len(code):
        c = code[j]
        if quote:
            if c == "\\":
                j += 2
                continue
            if c == quote:
                quote = None
        elif c in "'\"`":
            quote = c
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                break
        j += 1
    body = code[i:j + 1]
    out, checked = [], 0
    for call in re.finditer(r"\$t\s*\(", body):
        checked += 1
        k, depth, quote, args, buf = call.end(), 0, None, [], []
        while k < len(body):
            c = body[k]
            if quote:
                if c == "\\":
                    buf.append(c)
                    k += 1
                    if k < len(body):
                        buf.append(body[k])
                    k += 1
                    continue
                if c == quote:
                    quote = None
                buf.append(c)
            elif c in "'\"`":
                quote = c
                buf.append(c)
            elif c in "([{":
                depth += 1
                buf.append(c)
            elif c in ")]}":
                if depth == 0:
                    break                    # $t 呼叫的閉括號
                depth -= 1
                buf.append(c)
            elif c == "," and depth == 0:    # 頂層逗號＝引數分界
                args.append("".join(buf).strip())
                buf = []
            else:
                buf.append(c)
            k += 1
        args.append("".join(buf).strip())
        if args[-1] != fallback:             # 末個頂層引數不是原文 msg＝fallback 被吃掉
            out.append("$t(" + ", ".join(args) + ")")
    return out, checked


def self_test():
    base = "  content: response.data.msg,\n  other: keep,\n"
    bad = "  content: $t(x),\n  other: keep,\n"  # 改了 content、無原行 → 須攔
    # ★T069④：修改型樣本的軌道名一律用名冊內實名（B／I／L／R 四條原用 I18N-WIRING／UI／
    #   DEP 等名冊外短名——名冊斷言進場後，樣本自身就得是合規形，成對反例另列於下）。
    good = (
        "  // [rev5-inline BASE-WEB-I18N-WIRING(i)] 原行: content: response.data.msg,\n"
        "  content: $t(x),\n  other: keep,\n"
    )
    added = "  content: response.data.msg,\n  other: keep,\n  brandNew: 1,\n"  # 純新增、基線行未動
    assert find_missing(base, bad) == ["content: response.data.msg,"], "self-test A：應攔缺原行"
    assert find_missing(base, good) == [], "self-test B：有原行須過"
    assert find_missing(base, added) == [], "self-test C：純新增不誤判（find_missing 不管新增）"
    assert find_missing(base, bad + "brandNew: 1,\n") == ["content: response.data.msg,"], "self-test D：改+新增混合仍攔改的"

    # 補位 find_unmarked_additions（新增型圈界覆蓋；rev4:B-052）：
    marked_add = "  content: response.data.msg,\n  other: keep,\n  // [rev5-inline I18N-WIRING(ii)] 新鍵\n  brandNew: 1,\n"
    block_add = ("  content: response.data.msg,\n  other: keep,\n"
                 "  // [rev5-inline I18N-WIRING(ii) START] 區塊\n  a: 1,\n  b: 2,\n"
                 "  // [rev5-inline I18N-WIRING(ii) END]\n")
    comma_only = "  content: response.data.msg\n  other: keep,\n"     # 純去尾逗號、norm 相等
    # ★大寫 Generated by 落第 9 行（檔頭 8 行外）——令 head-limit 版該回 False、全檔搜尋版該回 True，
    #   K 才非 vacuous（對抗驗證 INT2：原用小寫字樣、大小寫敏感致兩版皆過、擋不住退化）。
    non_gen = "".join("import x from 'y';\n" for _ in range(8)) + "// routes Generated by a plugin\n"
    assert find_unmarked_additions(base, added) == ["brandNew: 1,"], "self-test E：純新增無圈界標記須攔"
    assert find_unmarked_additions(base, marked_add) == [], "self-test F：新增帶圈界標記須過"
    assert find_unmarked_additions(base, block_add) == [], "self-test G：START/END 圈界 block 須過"
    assert find_unmarked_additions(base, comma_only) == [], "self-test H：純尾標點差非新增、不誤判"
    assert find_unmarked_additions(base, good) == [], "self-test I：修改型帶原行標記、additive 檢查不誤報"
    assert is_generated("/* eslint-disable */\n// Generated by elegant-router\nx\n"), "self-test J：生成檔 header 須識別"
    assert not is_generated(non_gen), "self-test K：Generated by 於第 9 行（檔頭 8 行外）不豁免"

    # 對抗驗證修復回歸（change-block 級／區塊註解／結構豁免／標記限註解／++ 前綴）：
    b2 = "const o = {\n  title: 'Old',\n  keep1: 1,\n  keep2: 2,\n  keep3: 3,\n};\n"
    fn1 = ("const o = {\n  // [rev5-inline BASE-WEB-AUTH-WIRING(a) 003-auth-session] 原行: title: 'Old',\n  title: 'New',\n"
           "  keep1: 1,\n  newField: 9,\n  keep2: 2,\n  keep3: 3,\n};\n")
    struct = "function f() {\n  a();\n}\n"
    struct2 = "function f() {\n  // [rev5-inline X] guard\n  if (g) {\n  a();\n  }\n}\n"
    vbase = "<template>\n  <div>x</div>\n</template>\n"
    vadd = "<template>\n  <div>x</div>\n  <!--\n    multi line\n    comment\n  -->\n</template>\n"
    tbase = "const a = 1;\nconst b = 2;\n"
    tadd = "const a = 1;\n/*\nplain block comment\nline two\n*/\nconst b = 2;\n"
    sadd = 'a();\nlog("[rev5-inline] fake");\nb();\n'
    iadd = "let x = 1;\n++counter;\n"
    assert find_unmarked_additions(b2, fn1) == ["newField: 9,"], "self-test L：鄰近標記的未圈界實質新增仍須攔（FN1）"
    assert find_unmarked_additions(struct, struct2) == [], "self-test M：純結構標點新增（閉合 }）豁免、不誤報"
    assert find_unmarked_additions(vbase, vadd) == [], "self-test N：多行 HTML 區塊註解新增不誤報（FP1）"
    assert find_unmarked_additions(tbase, tadd) == [], "self-test O：多行 /* */ 純文字註解新增不誤報（FP2）"
    assert find_unmarked_additions("a();\nb();\n", sadd) == ['log("[rev5-inline] fake");'], "self-test P：字串內 [rev5-inline 非標記（FN2）"
    assert find_unmarked_additions("let x = 1;\n", iadd) == ["++counter;"], "self-test Q：++ 起首新增不因 +++ 前綴漏放（INT1）"
    # 第二輪對抗驗證新缺陷回歸（NF-A 同行閉合後碼／NF-B 空白鄰接獨立純新增／NF-C 同行連續 /* */）：
    nfb_base = "import foo from 'a';\n\nrun();\n"
    nfb = ("// [rev5-inline BASE-WEB-ADAPT 003-auth-session] 原行: import foo from 'a';\nimport foo from 'b';\n"
           "\nimport brandNew from 'c';\nrun();\n")
    nfa_base = "const o = {\n  a: 1,\n};\n"
    nfa = "const o = {\n  a: 1,\n  /* note\n     line\n  */ newFlag: true,\n};\n"
    nfc = "const a = 1;\n/* first */ /* second\n   inside\n*/\nconst b = 2;\n"
    assert find_unmarked_additions(nfb_base, nfb) == ["import brandNew from 'c';"], "self-test R：獨立純新增（空白鄰接標記修改）仍須攔（NF-B）"
    assert find_unmarked_additions(nfa_base, nfa) == ["*/ newFlag: true,"], "self-test S：區塊註解同行閉合後的新碼須被攔（NF-A）"
    assert find_unmarked_additions("const a = 1;\nconst b = 2;\n", nfc) == [], "self-test T：同行連續 /* */ /* 之第二註解 body 不誤報（NF-C）"

    # ── T069②：軌道名抽取正則——B-058 實測五種標記形逐形釘住 ──────────────────
    five_forms = [
        ("// [rev5-inline BASE-WEB-AUTH-WIRING(c)+ 003-auth-session] 圈界", "BASE-WEB-AUTH-WIRING"),
        ("// [rev5-inline BASE-WEB-AUTH-WIRING(a) 003-auth-session] 原行: y", "BASE-WEB-AUTH-WIRING"),
        ("// [rev5-inline BASE-WEB-LOGOUT-UX-WIRING(i)] 原行: y", "BASE-WEB-LOGOUT-UX-WIRING"),
        ("# [rev5-inline BASE-WEB-ADAPT 003-auth-session] .env 裸形", "BASE-WEB-ADAPT"),
        ("// [rev5-inline BASE-WEB-WRAPPER+ 003-auth-session] 新檔頭", "BASE-WEB-WRAPPER"),
    ]
    for line, want in five_forms:
        m = TRACK.search(line)
        assert m and m.group(1) == want, f"self-test U：五形抽取失準（{line!r} 應得 {want}、實得 {m and m.group(1)}）"

    # ── T069③④⑤：名冊斷言成對樣本（名冊內過／名冊外攔）＋裸原行攔＋新增型豁免 ──
    test_roster = {"BASE-WEB-I18N-WIRING", "BASE-WEB-AUTH-WIRING", "BASE-WEB-ADAPT"}
    for name, sample in (("B", good), ("L", fn1), ("R", nfb)):
        rogue, checked = find_rogue_tracks(sample, test_roster)
        assert rogue == [] and checked >= 1, f"self-test V：名冊內修改型樣本 {name} 須過且被計數（實得 {rogue}／checked={checked}）"
    rogue, checked = find_rogue_tracks(
        "  // [rev5-inline NOT-IN-ROSTER(i)] 原行: title: 'Old',\n  title: 'New',\n", test_roster)
    assert len(rogue) == 1 and "NOT-IN-ROSTER" in rogue[0][1] and checked == 1, \
        f"self-test W：名冊外軌道名須攔且指名（實得 {rogue}）"
    rogue, checked = find_rogue_tracks("  // 原行: content: response.data.msg,\n  content: $t(x),\n", test_roster)
    # ★錯因斷「前綴相等」而非「含 `[rev5-inline` 子字串」＋併斷 checked==0：另一條錯因字面
    #   「抽不出軌道名（標記形制不符 `[rev5-inline <TRACK>…]`）」本身就含該子字串，舊斷法
    #   兩條腿都過＝vacuous——實測把 token 強制那段整個刪掉後 self-test 與實掃仍全綠（變異 A2
    #   為 21 支變異中唯一漏網者）。checked 亦可區分：正解版對裸 `原行:` 回 0、變異版回 1。
    assert len(rogue) == 1 and rogue[0][1].startswith("缺 [rev5-inline token") and checked == 0, \
        f"self-test X：裸 `原行:`（無 token）須落『缺 token』分支且不入 checked（實得 {rogue}／checked={checked}）"
    for bad_form in ("  // [rev5-inline] 原行: title: 'Old',\n  title: 'New',\n",
                     "  // [rev5-inline lower(i)] 原行: title: 'Old',\n  title: 'New',\n"):
        rogue, checked = find_rogue_tracks(bad_form, test_roster)
        assert len(rogue) == 1 and rogue[0][1].startswith("抽不出軌道名") and checked == 1, \
            f"self-test X3：有 token 但抽不出軌道名須落該分支且計入 checked（實得 {rogue}／checked={checked}）"
    bare = "  // 原行: content: response.data.msg,\n  content: $t(x),\n  other: keep,\n"
    assert find_missing(base, bare) == ["content: response.data.msg,"], \
        "self-test X2：裸 `原行:` 不算已記錄——find_missing 仍須攔缺原行（T069③ 堵洗白）"
    rogue, checked = find_rogue_tracks(marked_add, test_roster)
    assert rogue == [] and checked == 0, \
        f"self-test Y：新增型標記（無 `原行:`）不入名冊射程（§III.2 表外宣告 3；實得 {rogue}／checked={checked}）"

    # ── B-061：假成功 toast 守——反例證真的攔得住、註解內字面不誤報 ─────────────
    toast_bad = "code();\nwindow.$message?.success($t('page.login.common.validateSuccess'));\n"
    toast_dot = "window.$message.success('x');\n"
    toast_good = ("// [rev5-inline BASE-WEB-AUTH-WIRING(b)] 消滅假成功 toast；原行: "
                  "window.$message?.success($t('page.login.common.validateSuccess'));\n"
                  "await stub();\n")
    # ★去註解「過頭」的恆綠形：字串常值內的 `/*` 令 `_code_of_line` 置位 closing、吞掉其後
    #   內容。兩條自證各抓一半——EOF 仍在註解態（Z6）＋未去註解命中數不為 1（Z4/Z5）。
    toast_swallowed = ("const marker = '/*';\n"
                       "window.$message?.success($t('page.login.common.validateSuccess'));\n")
    # 吞掉後又被別處的 `*/` 收掉＝EOF 乾淨，此時只剩「命中數 2」認得出 toast 已被插回來。
    toast_swallowed_closed = (toast_good + "const a = '/*';\n"
                              "window.$message?.success('back!');\nconst b = '*/';\n")
    toast_hollow = "await stub();\n"                     # 檔內根本沒有該字面＝第二欄 0
    assert find_fake_success_toast(toast_bad) == (
        ["window.$message?.success($t('page.login.common.validateSuccess'));"], 1), \
        "self-test Z1：$message?.success 呼叫須攔（B-061 反例）且未去註解命中數為 1"
    assert find_fake_success_toast(toast_dot) == (["window.$message.success('x');"], 1), \
        "self-test Z2：$message.success（點形）亦須攔"
    assert find_fake_success_toast(toast_good) == ([], 1), \
        "self-test Z3：字面僅在 `原行:` 註解內不得誤報（去註解是關鍵）、但第二欄須記到 1"
    assert find_fake_success_toast(toast_swallowed) == ([], 1), \
        "self-test Z4：字串常值內 `/*` 吞掉後續內容時違規清單空、第二欄仍為 1"
    assert find_fake_success_toast(toast_hollow) == ([], 0), \
        "self-test Z5：檔內零該字面須回第二欄 0——與 Z4 同回空清單，靠第二欄才可分辨"
    assert strip_ends_open(toast_swallowed) and not strip_ends_open(toast_good), \
        "self-test Z6：字串常值內 `/*` 須被認出（EOF 仍在註解態）、正常檔不得誤判"
    assert find_fake_success_toast(toast_swallowed_closed) == ([], 2) \
        and not strip_ends_open(toast_swallowed_closed), \
        ("self-test Z7：吞檔字面被別處 `*/` 收掉時 EOF 乾淨、違規清單仍空——"
         "只剩「未去註解命中數 ≠1」認得出 toast 已被插回來")

    # ── B-062：graceful fallback 守——反例＋函式界定不誤傷 translateDetailValue ──
    t_good = (
        "function translateDetailValue(msg, value) {\n"
        "  return value.map(item => $t(`${prefix}.${item}`, String(item)))"
        ".join($t('backend.common.listSeparator'));\n"
        "}\n"
        "function translateBackendMsg(msg, detail) {\n"
        "  const key = `backend.${msg}`;\n"
        "  if (!isPlainObject) return $t(key, msg);\n"
        "  const named = build(detail, msg);\n"
        "  return $t(key, named, msg);\n"
        "}\n"
    )
    t_bad = t_good.replace("return $t(key, msg);", "return $t(key);")
    # ★AD：三參形只被吃掉末參——舊判準（頂層引數 ≥2）漏放、實測變異證真；未命中鍵一樣顯裸
    #   `backend.*` 鍵，與 AB 同一違規面，故收窄為「末個頂層引數須為原文 msg」。
    t_bad2 = t_good.replace("return $t(key, named, msg);", "return $t(key, named);")
    # ★守門面被抽空的兩形（body 零 `$t(`）——回 `([], 0)`：違規清單空但 checked==0，
    #   由 scan_guard_targets 的 die 攔住。缺這組覆蓋時「零違規」與「全部合規」不可分辨。
    t_hollow = "function translateBackendMsg(msg, detail) {\n  return render(msg, detail);\n}\n"
    t_helper = (
        "function renderBackendText(key, detail) {\n  return $t(key);\n}\n"
        "function translateBackendMsg(msg, detail) {\n"
        "  return renderBackendText(`backend.${msg}`, detail);\n}\n"
    )
    assert find_bare_t_calls(t_good) == ([], 2), \
        "self-test AA：兩形帶 fallback 須過（且恰檢查 2 個呼叫）、函式外單參 $t（listSeparator）不得誤傷"
    assert find_bare_t_calls(t_bad) == (["$t(key)"], 2), "self-test AB：$t(key) 退化形須攔（B-062 反例）"
    assert find_bare_t_calls("const nothing = 1;\n")[0] != [], \
        "self-test AC：translateBackendMsg 結構性缺席須計違規（守門標的消失不得靜默放行）"
    assert find_bare_t_calls(t_bad2) == (["$t(key, named)"], 2), \
        "self-test AD：$t(key, named)（三參形被吃掉末參）退化形須攔（B-062 反例）"
    assert find_bare_t_calls(t_hollow) == ([], 0), \
        "self-test AE：函式在但 body 零 `$t(` 須回 checked=0（呼叫端據此 die、不得當全綠）"
    assert find_bare_t_calls(t_helper) == ([], 0), \
        "self-test AF：`$t` 被搬進 helper（fallback 在 helper 內被拔掉）亦須回 checked=0"


def assert_baseline():
    if not os.path.isdir(FORK):
        die(f"最原始源-基線目錄不存在：{FORK}")
    r = sh(["git", "rev-parse", "--abbrev-ref", "HEAD"], FORK)
    if r.returncode != 0:
        die(f"基線 repo 不可讀：{FORK}")
    cur = r.stdout.strip()
    if cur != BASELINE:
        die(f"最原始源-基線未就位：{FORK} 現在 '{cur}'、須切到 '{BASELINE}'"
            f"（git -C {FORK} checkout {BASELINE}）")


def changed_files():
    r = sh(["git", "diff", "--name-only", BASELINE, "--", "src/"], BASEWEB)
    if r.returncode != 0:
        die(f"無法 diff base-web vs {BASELINE}：{r.stderr.strip()}")
    return [f for f in r.stdout.splitlines() if f.endswith((".ts", ".vue"))]


def scan(roster):
    errs, unmarked, rogue = [], [], []
    checked_total = 0
    for rel in changed_files():
        base = sh(["git", "show", f"{BASELINE}:{rel}"], BASEWEB)
        if base.returncode != 0:
            continue  # 我方新檔（example 沒有）→ 豁免
        ours_path = os.path.join(BASEWEB, rel)
        try:
            ours = open(ours_path, encoding="utf-8").read()
        except FileNotFoundError:
            continue
        if is_generated(ours):
            continue  # 生成檔（elegant-router 等）→ fork-delta 由重算保證、豁免手標
        for m in find_missing(base.stdout, ours):
            errs.append((rel, m))
        for a in find_unmarked_additions(base.stdout, ours):
            unmarked.append((rel, a))
        hits, checked = find_rogue_tracks(ours, roster)
        checked_total += checked
        for line, why in hits:
            rogue.append((rel, line, why))
    return errs, unmarked, rogue, checked_total


def scan_guard_targets():
    """B-061／B-062 兩組語意守（逐檔列舉、與 diff 掃描面無關——upstream rebase 解錯即回歸、
    而 base-web 無測試 runner，這裡是唯一機器面）。守門標的檔缺席＝die（結構性缺席不放行）。"""
    toast_errs, t_errs, missing_lit = [], [], []
    for rel in FAKE_TOAST_FILES:
        path = os.path.join(BASEWEB, rel)
        if not os.path.isfile(path):
            die(f"B-061 守門標的不存在：{rel}——檔被移走／改名即守門面失效，先同步 FAKE_TOAST_FILES 名冊")
        content = open(path, encoding="utf-8").read()
        # B-061 結構性自證之一（形同下方 B-062 的 t_checked，但病灶在去註解面本身）：
        # 去註解掃完仍卡在區塊註解內＝字串常值裡的 `/*`／`<!--` 把其後內容整段吞掉，
        # 語意掃描從此對半個檔失明卻回零命中＝恆綠。真檔不可能這樣收尾，故一律 die。
        if strip_ends_open(content):
            die(f"B-061 守門標的 {rel} 去註解掃到 EOF 仍在區塊註解態——字串常值內的 `/*`／"
                f"`<!--` 已把其後內容整段吞掉，語意掃描面對該段失明卻回零命中（恆綠）；"
                f"修法＝令 `_code_of_line` 解析字串常值，或改寫該檔字面")
        hits, raw_hits = find_fake_success_toast(content)
        for hit in hits:
            toast_errs.append((rel, hit))
        if not hits and raw_hits != 1:
            # B-061 結構性自證之二：四支標的檔各在 `原行:` 註解裡逐字帶著
            # `$message?.success(…)`、且**恰一處**。0＝掃描面沒看到檔案內容（或標記已消失）；
            # ≥2＝多出一處被禁字面卻沒進違規清單（去註解走偏＋toast 被插回來同時發生的形，
            # 兩者本就會由同一次 upstream rebase 一起帶進來）。標的檔的 `原行:` 註解若因
            # upstream 前進而合法變動，修法＝同步本斷言（與 FAKE_TOAST_FILES 同一維護面）。
            die(f"B-061 守門標的 {rel} 未去註解時命中 `$message` success {raw_hits} 處（應恰 1"
                f"——即 `原行:` 註解裡那處）：0＝掃描面根本沒看到檔案內容、≥2＝多出一處被禁"
                f"字面卻未進違規清單；兩者皆令假 toast 防回歸面靜默失效")
    i18n_path = os.path.join(BASEWEB, I18N_FALLBACK_FILE)
    if not os.path.isfile(i18n_path):
        die(f"B-062 守門標的不存在：{I18N_FALLBACK_FILE}——先同步 I18N_FALLBACK_FILE 常數")
    violations, t_checked = find_bare_t_calls(open(i18n_path, encoding="utf-8").read())
    for v in violations:
        t_errs.append((I18N_FALLBACK_FILE, v))
    if not violations and t_checked < 1:
        # B-062 結構性自證（形沿 T069⑤ 的 checked_total 斷言）：真檔現況 body 內恰 2 個
        # `$t(` 呼叫。簽名還在、body 卻一個都沒掃到＝守門面已整個消失（body 被抽空、或
        # `$t` 被搬進 helper 而 fallback 在 helper 內被拔掉），此時「零違規」與「全部合規」
        # 在只回清單的形下無從分辨——不 die 就是恆綠放行。
        die(f"B-062 守門標的 {I18N_FALLBACK_FILE} 的 translateBackendMsg 函式體內零個 `$t(` "
            f"呼叫——守門面結構性消失（`$t` 被搬進 helper／body 被抽空即此形），"
            f"fallback 紀律不再受任何機器面約束（憲法 §III.2 I18N-WIRING(i)）")
    # ★交付面「必存字面」守：標的檔缺席或字面不見，兩者都是交付面消失，一律不放行。
    #   ★這組與上兩組方向相反（守「必須存在」而非「不得出現」），故不需 checked 計數
    #   自證——「檔讀不到」本身就 die、「讀到但沒命中」本身就是違規，兩態皆非恆綠。
    for rel, pat, why in REQUIRED_LITERALS:
        path = os.path.join(BASEWEB, rel)
        if not os.path.isfile(path):
            die(f"交付面守門標的不存在：{rel}——檔被移走／改名即守門面失效，先同步 REQUIRED_LITERALS 名冊")
        if not pat.search(open(path, encoding="utf-8").read()):
            missing_lit.append((rel, why))
    return toast_errs, t_errs, missing_lit


def main():
    try:
        self_test()
    except AssertionError as e:
        die(f"self-test 失敗（lint 邏輯壞）：{e}")
    roster = load_roster()  # 含 T069⑤ 三重斷言（空名冊／★段列數／散文反例＝die）
    assert_baseline()
    tip = sh(["git", "rev-parse", "--short", BASELINE], BASEWEB).stdout.strip()
    errs, unmarked, rogue, checked_total = scan(roster)
    if checked_total < 1:
        # T069⑤ 結構性自證：真 repo 現有至少兩個修改型對象（B-058：route/index.ts 的 (a)、
        # user-avatar.vue 的 (i)）——一個都沒檢查到＝changed_files／掃描面壞掉、名冊斷言恆綠。
        die("真 repo 未檢查到任何修改型標記——掃描面失效、名冊斷言 vacuous（T069⑤ 結構性自證）")
    toast_errs, t_errs, missing_lit = scan_guard_targets()
    if errs or unmarked or rogue or toast_errs or t_errs or missing_lit:
        if errs:
            print(f"[fork-delta-lint] ✗ {len(errs)} 條 example 上游 inline 行被改動卻缺 `原行:` 標記"
                  f"（constitution §III L114；基線 {BASELINE}@{tip}）：")
            for rel, m in errs:
                print(f"    {rel}｜缺 原行: {m}")
            print("  補法：緊鄰改動行之上加 `// [rev5-inline <track>] 原行: <上列原碼>`。")
        if unmarked:
            print(f"[fork-delta-lint] ✗ {len(unmarked)} 個新增碼區塊缺 rev5-inline 圈界標記"
                  f"（constitution §III 新增型圈界；基線 {BASELINE}@{tip}）：")
            for rel, a in unmarked:
                print(f"    {rel}｜未圈界新增首行: {a}")
            print("  補法：新增區塊上方加 `// [rev5-inline <track> <feature>] <說明>`；"
                  "大區塊用 START…END 圈界。生成檔（Generated by header）自動豁免。")
        if rogue:
            print(f"[fork-delta-lint] ✗ {len(rogue)} 個修改型標記的軌道名不在授權名冊"
                  f"（T069；constitution §III.2 名冊＝★軌道 ∪ §III.1 三軌道）：")
            for rel, line, why in rogue:
                print(f"    {rel}｜{why}｜{line}")
            print("  補法：軌道名改用名冊內實名；新用途／新軌道須先走 §V.2 Amendment 開立。")
        if toast_errs:
            print(f"[fork-delta-lint] ✗ {len(toast_errs)} 處假成功 toast 回歸"
                  f"（B-061；U-M 已消滅之 `$message` success 呼叫不得回歸）：")
            for rel, hit in toast_errs:
                print(f"    {rel}｜{hit}")
            print("  補法：移除 success toast——三表單走誠實 stub（恆 2222）、送碼 hook 成功即倒數。")
        if missing_lit:
            print(f"[fork-delta-lint] ✗ {len(missing_lit)} 處交付面必存字面消失"
                  f"（upstream rebase 選了 upstream 版、或該行被「清理」——五道閘皆看不見）：")
            for rel, why in missing_lit:
                print(f"    {rel}｜{why}")
        if t_errs:
            print(f"[fork-delta-lint] ✗ {len(t_errs)} 個 `$t(` 呼叫缺 fallback 引數"
                  f"（B-062；憲法 §III.2 I18N-WIRING(i)：未命中 MUST graceful fallback、不得顯裸 key）：")
            for rel, v in t_errs:
                print(f"    {rel}｜{v}")
            print("  補法：改 `$t(key, msg)` 或 `$t(key, named, msg)`（末參＝原文 fallback）。")
        sys.exit(1)
    print(f"[fork-delta-lint] ✓ base-web 修改型全帶原行（軌道名 {checked_total} 處皆在名冊）、"
          f"新增型全圈界；B-061 假 toast／B-062 $t fallback／交付面必存字面 三守綠"
          f"（self-test 過；基線 {BASELINE}@{tip}）")


if __name__ == "__main__":
    main()
