#!/usr/bin/env python3
"""tools/fork-delta-lint.py — 機器式驗 base-web fork-delta「原行」紀律（constitution §III L114）。

最原始源-基線＝`fork260509-soybean-admin-base/` @ `example` 分支 tip（實體目錄、須先切到）。
判定：base-web 若改動 example 既有 inline 行（該行不再逐字存在於我方版）→ 我方檔內**必須**有
`// [rev5-inline …] 原行: <example 那行原始內容>` 標記、且 `原行:` 後內容＝基線該行（正規化後相等）。
缺 → 紅、指名「檔:上游原行」。我方新檔／純新增行（example 沒有）不要求原行。

★補位（B-052）：新增型（基線沒有的新行）雖不要原行，但依 §III 須走「新增型圈界」rev5-inline
標記——`find_unmarked_additions` 補這道，令「所有 fork-delta（修改＋新增）皆帶 rev5-inline 標記、
上游 rebase 可定位」。機器生成檔（Generated by header）由重算保證 fork-delta、豁免手標。

每次執行**先跑 self-test**（合成缺原行/缺圈界樣本、證 lint 真能攔——防 vacuous 恆綠），再跑實掃。
"""
import difflib
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASEWEB = os.path.join(REPO, "base-web")
FORK = os.path.join(REPO, "fork260509-soybean-admin-base")
BASELINE = "example"

MARKER = re.compile(r"原行:\s*(.*\S)\s*$")


def die(msg):
    print(f"[fork-delta-lint] ✗ {msg}", file=sys.stderr)
    sys.exit(2)


def sh(args, cwd):
    # 清掉 GIT_* env：git hook 會把外層 repo 的 GIT_DIR/GIT_INDEX_FILE 洩漏給子行程，
    # 害對 base-web worktree（.git 為檔）跑 git 抓錯 index（.git/index: Not a directory）。
    env = {k: v for k, v in os.environ.items() if not k.startswith("GIT_")}
    return subprocess.run(args, cwd=cwd, capture_output=True, text=True, env=env)


def is_code(line):
    s = line.strip()
    return bool(s) and not s.startswith(("//", "/*", "*", "<!--"))


def norm(line):
    # 去尾端逗號/分號：加新同層條目使前一行多尾逗號，屬新增型副作用、非語意改變（§III「語意被改變」才算修改型）
    return line.strip().rstrip(",;").rstrip()


def find_missing(base_content, ours_content):
    """回傳「基線有、我方既無此行、又無對應原行標記」的上游**原行**（供逐字補回）。
    ★比對用 norm（去尾標點）、輸出保原行原貌（含尾逗號等）。"""
    ours = ours_content.splitlines()
    ours_lines = {norm(l) for l in ours}
    recorded = set()
    for l in ours:
        m = MARKER.search(l)
        if m:
            recorded.add(norm(m.group(1)))
    seen = set()
    missing = []
    for raw in base_content.splitlines():
        if not is_code(raw):
            continue
        n = norm(raw)
        if not n or n in ours_lines or n in recorded or n in seen:
            continue
        seen.add(n)
        missing.append(raw.strip())  # 原行原貌（去首尾空白、保尾逗號）
    return missing


def is_generated(content):
    """檔頭 8 行含生成器標記＝機器生成檔（elegant-router／unplugin 等）：fork-delta 由重算保證、
    不手標圈界，故豁免。★限檔頭（避免誤中 hand-written 檔散文裡的『auto generated』字樣——
    如 store/modules/route/index.ts 第 36 行、theme/shared.ts 第 264 行）。"""
    head = "\n".join(content.splitlines()[:8])
    return bool(re.search(r"Generated by|@generated", head))


def _block_code_added(added):
    """回 added 各『去註解後仍有實質碼』的行（原行原貌）。★逐行內字元掃描、正確處理跨行 /* */、
    <!-- --> 之開閉——含『同行閉合後緊接碼』（對抗驗證 NF-A：`*/ code` 不再整行丟棄）與『同行連續
    /* */ /* …』（對抗驗證 NF-C：第二註解 body 不洩為碼）；行註解 // 到行尾。"""
    out, closing = [], None
    for l in added:
        rest, code = l, ""
        while rest:
            if closing:                      # 在跨行區塊註解內、找閉合
                k = rest.find(closing)
                if k < 0:
                    rest = ""
                else:
                    rest, closing = rest[k + len(closing):], None
                continue
            cands = [(rest.find(t), t) for t in ("//", "/*", "<!--") if t in rest]
            if not cands:
                code += rest
                break
            i, t = min(cands)
            code += rest[:i]
            if t == "//":
                break                        # 行註解到行尾
            closing, rest = ("*/" if t == "/*" else "-->"), rest[i + len(t):]
        if code.strip():
            out.append(l)
    return out


def _structural_only(line):
    """純結構標點行（}、);、],… 無任何識別碼字元）＝區塊延續、不需獨立圈界（避免對閉合括號誤報）。"""
    return not re.search(r"[0-9A-Za-z_$]", line)


def _block_has_marker(added):
    """change-block 內有無合法 rev5 標記——限『註解行』且含 [rev5-inline（排除字串常值內同名子字串
    的自我認證：對抗驗證 FN2）。"""
    return any(s.startswith(("//", "/*", "*", "<!--")) and "[rev5-inline" in s
               for s in (l.strip() for l in added))


def find_unmarked_additions(base_content, ours_content):
    """回「新增碼 change-block 卻無合法 rev5-inline 標記」之首個實質新增行（供補圈界標記）。★補位
    find_missing（後者驗修改型缺原行）；本函式驗新增型缺圈界，合起來令所有 fork-delta 皆帶標記。
    §III 新增型圈界紀律。

    以 difflib.unified_diff 取差異、按 **change-block**（連續 +/- 行為一塊、context 行〔含空白〕分界）；
    ★只驗『純新增塊』（塊內無任何被移除碼行）——含被移除碼行者＝修改型/替換區塊、由 find_missing
    驗原行、本函式跳過（故 captcha 型『替換邏輯與其原行標記被空白 context 分隔』不誤報）。純新增塊去
    （跨行）註解＋純結構標點行（閉合 } 等＝區塊延續）後仍有實質新增碼卻無合法標記（限註解行、字串
    常值內子字串不算）→報首行。分工：修改型缺原行→find_missing；純新增（新 import/欄位）缺圈界→本函式。
    ★已知可接受殘留（2 輪對抗驗證後定；見 LESSONS）：①與修改型同塊（無 context 分隔）的額外未圈界
    新增歸該塊原行標記涵蓋、不另報（修它會重引入 captcha 型替換誤報張力）；②字串常值內未閉合 /* 之
    後續行罕見被當註解（窄 FN；不做 string-parsing）。假 DEL 洗白被 find_missing『刪行缺原行』兜住。"""
    out = []
    added, removed = [], []
    seen_hunk = False

    def flush():
        if any(is_code(l) for l in removed):
            return                           # 修改型/替換塊（含移除碼）→ 歸 find_missing、本函式跳過
        substantive = [l for l in _block_code_added(added) if not _structural_only(l)]
        if substantive and not _block_has_marker(added):
            out.append(substantive[0].strip())

    for line in difflib.unified_diff(base_content.splitlines(),
                                     ours_content.splitlines(), n=3, lineterm=""):
        if line.startswith("@@"):
            flush(); added, removed = [], []; seen_hunk = True
        elif not seen_hunk:
            continue                         # unified_diff 檔頭 ---/+++（首個 @@ 前）——seen_hunk 旗標
        elif line.startswith("+"):           # 認檔頭，內容以 ++/-- 起首不撞 +++/---（對抗驗證 INT1）
            added.append(line[1:])
        elif line.startswith("-"):
            removed.append(line[1:])
        else:                                # context 行（含空白）＝ change-block 分界
            flush(); added, removed = [], []
    flush()
    return out


def self_test():
    base = "  content: response.data.msg,\n  other: keep,\n"
    bad = "  content: $t(x),\n  other: keep,\n"  # 改了 content、無原行 → 須攔
    good = (
        "  // [rev5-inline I18N-WIRING(i)] 原行: content: response.data.msg,\n"
        "  content: $t(x),\n  other: keep,\n"
    )
    added = "  content: response.data.msg,\n  other: keep,\n  brandNew: 1,\n"  # 純新增、基線行未動
    assert find_missing(base, bad) == ["content: response.data.msg,"], "self-test A：應攔缺原行"
    assert find_missing(base, good) == [], "self-test B：有原行須過"
    assert find_missing(base, added) == [], "self-test C：純新增不誤判（find_missing 不管新增）"
    assert find_missing(base, bad + "brandNew: 1,\n") == ["content: response.data.msg,"], "self-test D：改+新增混合仍攔改的"

    # 補位 find_unmarked_additions（新增型圈界覆蓋；B-052）：
    marked_add = "  content: response.data.msg,\n  other: keep,\n  // [rev5-inline I18N-WIRING(ii)] 新鍵\n  brandNew: 1,\n"
    block_add = ("  content: response.data.msg,\n  other: keep,\n"
                 "  // [rev5-inline I18N-WIRING(ii) START] 區塊\n  a: 1,\n  b: 2,\n"
                 "  // [rev5-inline I18N-WIRING(ii) END]\n")
    comma_only = "  content: response.data.msg\n  other: keep,\n"     # 純去尾逗號、norm 相等
    # ★大寫 Generated by 落第 9 行（檔頭 8 行外）——令 head-limit 版該回 False、全檔搜尋版該回 True，
    #   K 才非 vacuous（對抗驗證 INT2：原用小寫字樣、大小寫敏感致兩版皆過、擋不住退化）。
    non_gen = "".join("import x from 'y';\n" for _ in range(8)) + "// routes Generated by a plugin\n"
    assert find_unmarked_additions(base, added) == ["brandNew: 1,"], "self-test E：純新增無圈界標記須攔"
    assert find_unmarked_additions(base, marked_add) == [], "self-test F：新增帶圈界標記須過"
    assert find_unmarked_additions(base, block_add) == [], "self-test G：START/END 圈界 block 須過"
    assert find_unmarked_additions(base, comma_only) == [], "self-test H：純尾標點差非新增、不誤判"
    assert find_unmarked_additions(base, good) == [], "self-test I：修改型帶原行標記、additive 檢查不誤報"
    assert is_generated("/* eslint-disable */\n// Generated by elegant-router\nx\n"), "self-test J：生成檔 header 須識別"
    assert not is_generated(non_gen), "self-test K：Generated by 於第 9 行（檔頭 8 行外）不豁免"

    # 對抗驗證修復回歸（change-block 級／區塊註解／結構豁免／標記限註解／++ 前綴）：
    b2 = "const o = {\n  title: 'Old',\n  keep1: 1,\n  keep2: 2,\n  keep3: 3,\n};\n"
    fn1 = ("const o = {\n  // [rev5-inline UI(i)] 原行: title: 'Old',\n  title: 'New',\n"
           "  keep1: 1,\n  newField: 9,\n  keep2: 2,\n  keep3: 3,\n};\n")
    struct = "function f() {\n  a();\n}\n"
    struct2 = "function f() {\n  // [rev5-inline X] guard\n  if (g) {\n  a();\n  }\n}\n"
    vbase = "<template>\n  <div>x</div>\n</template>\n"
    vadd = "<template>\n  <div>x</div>\n  <!--\n    multi line\n    comment\n  -->\n</template>\n"
    tbase = "const a = 1;\nconst b = 2;\n"
    tadd = "const a = 1;\n/*\nplain block comment\nline two\n*/\nconst b = 2;\n"
    sadd = 'a();\nlog("[rev5-inline] fake");\nb();\n'
    iadd = "let x = 1;\n++counter;\n"
    assert find_unmarked_additions(b2, fn1) == ["newField: 9,"], "self-test L：鄰近標記的未圈界實質新增仍須攔（FN1）"
    assert find_unmarked_additions(struct, struct2) == [], "self-test M：純結構標點新增（閉合 }）豁免、不誤報"
    assert find_unmarked_additions(vbase, vadd) == [], "self-test N：多行 HTML 區塊註解新增不誤報（FP1）"
    assert find_unmarked_additions(tbase, tadd) == [], "self-test O：多行 /* */ 純文字註解新增不誤報（FP2）"
    assert find_unmarked_additions("a();\nb();\n", sadd) == ['log("[rev5-inline] fake");'], "self-test P：字串內 [rev5-inline 非標記（FN2）"
    assert find_unmarked_additions("let x = 1;\n", iadd) == ["++counter;"], "self-test Q：++ 起首新增不因 +++ 前綴漏放（INT1）"
    # 第二輪對抗驗證新缺陷回歸（NF-A 同行閉合後碼／NF-B 空白鄰接獨立純新增／NF-C 同行連續 /* */）：
    nfb_base = "import foo from 'a';\n\nrun();\n"
    nfb = ("// [rev5-inline DEP] 原行: import foo from 'a';\nimport foo from 'b';\n"
           "\nimport brandNew from 'c';\nrun();\n")
    nfa_base = "const o = {\n  a: 1,\n};\n"
    nfa = "const o = {\n  a: 1,\n  /* note\n     line\n  */ newFlag: true,\n};\n"
    nfc = "const a = 1;\n/* first */ /* second\n   inside\n*/\nconst b = 2;\n"
    assert find_unmarked_additions(nfb_base, nfb) == ["import brandNew from 'c';"], "self-test R：獨立純新增（空白鄰接標記修改）仍須攔（NF-B）"
    assert find_unmarked_additions(nfa_base, nfa) == ["*/ newFlag: true,"], "self-test S：區塊註解同行閉合後的新碼須被攔（NF-A）"
    assert find_unmarked_additions("const a = 1;\nconst b = 2;\n", nfc) == [], "self-test T：同行連續 /* */ /* 之第二註解 body 不誤報（NF-C）"


def assert_baseline():
    if not os.path.isdir(FORK):
        die(f"最原始源-基線目錄不存在：{FORK}")
    r = sh(["git", "rev-parse", "--abbrev-ref", "HEAD"], FORK)
    if r.returncode != 0:
        die(f"基線 repo 不可讀：{FORK}")
    cur = r.stdout.strip()
    if cur != BASELINE:
        die(f"最原始源-基線未就位：{FORK} 現在 '{cur}'、須切到 '{BASELINE}'"
            f"（git -C {FORK} checkout {BASELINE}）")


def changed_files():
    r = sh(["git", "diff", "--name-only", BASELINE, "--", "src/"], BASEWEB)
    if r.returncode != 0:
        die(f"無法 diff base-web vs {BASELINE}：{r.stderr.strip()}")
    return [f for f in r.stdout.splitlines() if f.endswith((".ts", ".vue"))]


def scan():
    errs, unmarked = [], []
    for rel in changed_files():
        base = sh(["git", "show", f"{BASELINE}:{rel}"], BASEWEB)
        if base.returncode != 0:
            continue  # 我方新檔（example 沒有）→ 豁免
        ours_path = os.path.join(BASEWEB, rel)
        try:
            ours = open(ours_path, encoding="utf-8").read()
        except FileNotFoundError:
            continue
        if is_generated(ours):
            continue  # 生成檔（elegant-router 等）→ fork-delta 由重算保證、豁免手標
        for m in find_missing(base.stdout, ours):
            errs.append((rel, m))
        for a in find_unmarked_additions(base.stdout, ours):
            unmarked.append((rel, a))
    return errs, unmarked


def main():
    try:
        self_test()
    except AssertionError as e:
        die(f"self-test 失敗（lint 邏輯壞）：{e}")
    assert_baseline()
    tip = sh(["git", "rev-parse", "--short", BASELINE], BASEWEB).stdout.strip()
    errs, unmarked = scan()
    if errs or unmarked:
        if errs:
            print(f"[fork-delta-lint] ✗ {len(errs)} 條 example 上游 inline 行被改動卻缺 `原行:` 標記"
                  f"（constitution §III L114；基線 {BASELINE}@{tip}）：")
            for rel, m in errs:
                print(f"    {rel}｜缺 原行: {m}")
            print("  補法：緊鄰改動行之上加 `// [rev5-inline <track>] 原行: <上列原碼>`。")
        if unmarked:
            print(f"[fork-delta-lint] ✗ {len(unmarked)} 個新增碼區塊缺 rev5-inline 圈界標記"
                  f"（constitution §III 新增型圈界；基線 {BASELINE}@{tip}）：")
            for rel, a in unmarked:
                print(f"    {rel}｜未圈界新增首行: {a}")
            print("  補法：新增區塊上方加 `// [rev5-inline <track> <feature>] <說明>`；"
                  "大區塊用 START…END 圈界。生成檔（Generated by header）自動豁免。")
        sys.exit(1)
    print(f"[fork-delta-lint] ✓ base-web 修改型全帶原行、新增型全圈界"
          f"（self-test 過；基線 {BASELINE}@{tip}）")


if __name__ == "__main__":
    main()
