#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""tools/route-artifact-gate.py — 路由外掛產物檔的重算冪等閘（憲法 §III.2 第五列／ADR 0040 款三）

子命令：
  check   （預設）三道斷言：①產出檔集對賬 ②重算冪等（版控為種）③零手改（基線為種）
          `--constitution <path>` 可指向替代憲法檔——**僅供守門自身的變異驗證**，
          日常一律用預設路徑（不帶該旗標）
  test    只跑自帶 self-test（離線、不需 docker／node、毫秒級）

════════ 為何非有不可 ════════

`src/router/elegant/{imports,routes,transform}.ts` 與 `src/typings/elegant-router.d.ts`
這四支是路由外掛（`@elegant-router/vue`，掛在 `build/plugins/router.ts`）**重算產出**的檔案。
憲法 §III.2 第五列對它們採「產物檔紀律」：禁止手改、且**不要求逐行 `原行:` 標記**——因為
標記在下一次重算就會被抹掉，寫進紀律等於立一條保證會被違反的規則。

代價是這四支**同時被 fork-delta 檢查全域豁免**（`tools/fork-delta-lint.py` 對帶
`Generated by …` 檔頭者豁免手標）。也就是說：**沒有本閘，這四支檔一行機器守都沒有**。
任何人（含未來的自己）在裡頭手改一行——調一條 route 的 path、刪掉一個 RouteKey、把某頁
的 component 指到別處——不會有任何檢查出聲，而錯誤要等到執行期才以「頁面 404」「側邊欄
少一項」的形式出現，且第一嫌疑犯永遠會是別的東西。

★**刪掉本閘會怎樣**：上述覆蓋缺口立即成真，憲法那一列的「驗收改採重算冪等檢查」變成一句
沒有實體的話。★**改壞被測物會怎樣**：手改四支中任一支的任一行 → 第③道斷言當場紅並印出
逐行 diff——下方 self-test 的 F 段**實跑生產函式 `compare_against_worktree`**（把它的工作樹
根與 sh 執行面注入成暫存目錄＋host sh），先證兩側逐位相同時判綠、再手改工作樹側一行證其判紅。
★**F 段刻意不寫成「另比一次 bytes」**：那種寫法只是斷言兩個建構即不同的字串不相等，守門就算
整支失效也照樣通過（ADR 0024 決定①所禁的 vacuous 形），對「這道守門攔不攔得住」零資訊量。

════════ 三道斷言各自守什麼 ════════

**①產出檔集對賬**（憲法漏列一支＝該支完全無守）
  `G_a`＝在**空沙盒**跑一次外掛、觀測它實際寫出哪些檔（不預設任何清單——寫死清單就是把
        「外掛產出什麼」這個待驗事實當成前提）
  `G_h`＝`base-web/src/**` 底下檔頭帶 `Generated by elegant-router` 的檔集
  `G_c`＝憲法 §III.2 第五列**範圍欄**列出的全部檔案路徑（`{a,b}` 花括號群組展開）
  斷言 `G_a == G_h`（外掛產出的就是掛著產物檔頭的那些）且 `G_a ⊆ G_c`（憲法列全數涵蓋）。
  ★`⊆` 而非 `==` 是**刻意的**：該列的範圍欄同時列著兩語 locale 與 `app.d.ts` 三支**非產物**
  檔（那三支走圈界標記紀律），機器無法從中文散文可靠切出「哪幾支是產物」。取全欄路徑做
  上界，即滿足憲法要求的「本列漏列一支即紅」，又不會因為該列同時列著非產物檔而誤報。
  ★殘留缺口（誠實揭露）：若有人把某支產物路徑「搬到」該列的非產物敘述段落而路徑字面不變，
  本斷言看不出來——但那支檔的**內容**仍受第②③道守著，實害為零。

**②重算冪等**（種＝版控現況）
  把版控的四支複製進沙盒、以 rev5 現行 view 樹重跑外掛 → 必須 byte 相等。
  這道守的是「版控內容已收斂」：新增一支 view 卻忘了讓外掛重算（或重算後沒 commit），
  本道即紅——那正是「側邊欄少一項」的成因。

**③零手改**（種＝上游基線）
  把**上游基線**（`fork260509-soybean-admin-base`，恆切在 `example` tip）的四支複製進沙盒、
  以 rev5 現行 view 樹重跑外掛 → 必須 byte 相等於版控。
  ★這道**不可省**，且強度嚴格高於第②道。原因是外掛對 `routes.ts` 走的是 magicast **增量
  合併**（只補缺的 route、保留既有條目），所以「以版控為種」重跑時，手改過的那一行會原封
  不動地活下來、第②道全綠（已實測：把某條 route 的 `i18nKey` 改掉後重跑，改動存活）。
  以基線為種重算則整份內容都是算出來的，任何手改都無處可藏。
  ★這也解釋了為何本閘要求基線源倉在位（同 `fork-delta-lint` 的既有前提）：基線缺席時本道
  具名跳過並降級為警告，**不靜默**。
  ★既然第③道強度嚴格高於第②道，為何仍保留第②道？兩個理由：一、基線缺席（fresh clone
  未跑 bootstrap）時第③道跳過，第②道是當下唯一還在跑的重算斷言；二、憲法第五列的驗收
  逐字就是「重跑外掛後與版控內容零差異」，第②道即該句的直譯，刪掉它等於讓實作與條文對不上。

════════ 落點：為何**不**掛 pre-commit ════════

本閘要在容器內實跑 vite 外掛三趟（空沙盒觀測＋兩道種子重算），每趟含一次 TS 動態載入與
整棵 view 樹掃描，實測合計十餘秒。`pre-commit` 的全鏈預算是**秒級**（`.githooks/pre-commit`
自帶 20s 警戒／45s 硬擋兩級門檻，且該門檻調整須走 ADR），把本閘無條件掛上去等於一個人
改 README 也要付十幾秒——那是養成 `--no-verify` 慣性的標準配方，而 `--no-verify` 一旦成為
習慣，同一份 hook 上的**事件型**檢查（機密掃描）會跟著失效，代價不可逆。

故本閘定位為**單元邊界／CI 呼叫的獨立指令**：`python3 tools/route-artifact-gate.py check`。
被守的四支檔只在「新增／搬移 view 檔」或「動路由外掛設定」時才會變，那恰好是單元邊界事件，
不是每次 commit 都發生的事。★另一個不掛的硬理由：本閘依賴 dev stack 在跑（容器內才有
node_modules），而 pre-commit MUST 在 stack 沒起時照樣可用。

★**尚未入治理名冊**——下列五處皆在本刀 U-I 的授權檔集外，已逐處以 escalation 升級主線
（★逐處寫出、不寫「等」：漏列的那一處就是不會被補的那一處）：
  ①`docs/ops/RUNBOOK.md` §12 工具表──未列本檔（該表是「跑哪支指令」的查詢入口，
    而本閘的排程落點正好不是 pre-commit ⇒ 不進該表就等於沒有任何地方告訴人它該被跑）。
  ②`tools/docs-sync.py` 的 `TOOLS_PY` 真表 ③`tools/bootstrap.sh` 的 `run_tool_test` 行
    ──兩處與 pre-commit 的 `for t in …` 名冊三方逐字對賬，要接就得同批動。★接與不接是
    拍板級：本閘的 `test` 子命令離線毫秒級（可入體檢），但 `check` 需 dev stack ⇒ 若日後
    決定接線，只該接 `test`、不可讓 bootstrap 無條件跑 `check`。
  ④`README.md` 的 `tools/` 目錄樹──該樹逐支列出 `tools/` 底下全部檔案（現列 8 支），
    本檔與 `tools/view-render-guard.py` 皆不在其中；CLAUDE.md 明載「repo 目錄樹全景→
    README.md」⇒ 該樹是這個集合的單一權威家，且**無任何機器兜底**（`docs-sync.py lint`
    對 README 只做命令形檢查，樹失準照樣全綠）。
  ⑤`docs/arc42/ARCHITECTURE.md` 之「fork-delta 接線現況（base-web）」★軌道名冊──該節逐條
    寫出軌道的用途／實際接線檔／機器守，但只有**四條**；憲法 §III.2 已有**五條**，缺的正是
    本閘所守的 ★`BASE-WEB-MANAGE-PAGE-WIRING`。★這不是體例問題而是**漏跟**：該節是現在式
    活書（同節 I18N-WIRING 那條的 backend 鍵數逐刀跟到最新——★此處刻意**不複述數字**：複述一個逐刀會變的計數，就是替自己排一次必然的失準），而
    本軌道的接線檔（兩語 locale `route:`／`page:` 兩樹、`app.d.ts` 型節、路由外掛產物四檔）
    **在本單元之前一支都不存在**——是 U-I 讓它從紙面變成實體，故「活書永遠現在式」自本單元
    起不成立。★該節同段落的機器守句亦須連帶補上本閘（產物四檔受 fork-delta **全域豁免**，
    本閘是它們唯一的機器守，漏記＝讀活書的人會以為那四支歸 fork-delta-lint 管）。
    〔軌道本身由 U-A／ADR 0040 開立，該節是否當時就該補屬 U-A 帳；但本單元的枚舉義務涵蓋
    它，且它不在任何人的待辦上。〕
"""
import json
import os
import re
import subprocess
import sys
import tempfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CONSTITUTION_REL = os.path.join(".specify", "memory", "constitution.md")
BASE_WEB_REL = "base-web"
BASELINE_REL = "fork260509-soybean-admin-base"

# 憲法 §III.2 表中的目標列（軌道名×用途識別符）——ADR 0040 款三所開之第五條 ★ 軌道。
TRACK_NAME = "BASE-WEB-MANAGE-PAGE-WIRING"
TRACK_PURPOSE = "(i)"

# 產物檔的辨識檔頭（外掛自己寫的；`fork-delta-lint.py` 亦以同字樣豁免手標）。
GENERATED_HEADER = "Generated by elegant-router"
GENERATED_HEADER_MAX_LINE = 8

COMPOSE = ["docker", "compose", "-f", "docker-compose.yml", "-f", "docker-compose.dev.yml"]
BASE_WEB_EXEC = COMPOSE + ["exec", "-T", "base-web"]

START_HINT = "docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --wait"

# 容器內沙盒根（每道斷言各自一顆、跑完即刪）。
SANDBOX_ROOT = "/tmp/route-artifact-gate"

# 沙盒內的 node 執行器：載入 rev5 **現行**外掛設定（`build/plugins/router.ts`，經 node 型別剝除
# 直接吃 TS），讓外掛以沙盒為 cwd 產出，再等檔案系統靜止後印出它實際寫了哪些檔。
# ★設定不在本檔重抄一份：抄一份就等於多一個會漂移的真相源，而本閘要驗的正是「外掛照設定
#   算出來的東西」。cwd 即外掛的輸出根（`dtsDir` 等預設路徑相對 cwd 解析）。
NODE_RUNNER = r"""
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();

// 只走真目錄與真檔（沙盒的 src/views、src/layouts、node_modules 是 symlink，一律不下探）
function walk(dir, base, out) {
  for (const name of fs.readdirSync(dir).sort()) {
    const abs = path.join(dir, name);
    const rel = base ? `${base}/${name}` : name;
    const st = fs.lstatSync(abs);
    if (st.isSymbolicLink()) continue;
    if (st.isDirectory()) walk(abs, rel, out);
    else if (st.isFile()) out[rel] = `${st.size}:${st.mtimeMs}`;
  }
}

function snap() {
  const out = {};
  if (fs.existsSync(path.join(root, 'src'))) walk(path.join(root, 'src'), 'src', out);
  return out;
}

const sleep = ms => new Promise(r => setTimeout(r, ms));

const t0 = Date.now();
const mod = await import('/app/build/plugins/router.ts');
mod.setupElegantRouter();   // ★產出是建構子的副作用，外掛未曝出可 await 的 promise

// 等到「檔案都出現且都被本輪重寫過（mtime ≥ t0）、且連續三次快照無變化」為止。
// 純睡固定秒數在慢機器上會取到寫到一半的內容——那種失敗看起來會像 flaky。
let prev = null;
let stable = 0;
let ok = false;
const deadline = Date.now() + 90000;
while (Date.now() < deadline) {
  await sleep(250);
  const cur = snap();
  const names = Object.keys(cur);
  const fresh = names.length > 0 && names.every(n => Number(cur[n].split(':')[1]) >= t0);
  const json = JSON.stringify(cur);
  if (fresh && json === prev) {
    stable += 1;
    if (stable >= 3) { ok = true; break; }
  } else {
    stable = 0;
  }
  prev = json;
}
if (!ok) {
  console.error('[runner] 外掛產出未在 90s 內靜止——沙盒狀態：' + prev);
  process.exit(3);
}
console.log('__FILES__' + JSON.stringify(Object.keys(JSON.parse(prev))));
"""


class GateError(Exception):
    """環境不可用／前提不成立——rc=2（與「檢查判定為紅」的 rc=1 分流）。"""


# ── 憲法 §III.2 表列解析 ────────────────────────────────────────────────────────

# 花括號群組：`src/router/elegant/{imports,routes,transform}.ts`
_RE_BRACE = re.compile(r"^(.*?)\{([^{}]+)\}(.*)$")
# 範圍欄內的反引號路徑字面（限 src/ 起首、含副檔名——避免抓到散文裡的其他反引號片語）
_RE_PATH = re.compile(r"`(src/[^`]+?\.(?:ts|vue|d\.ts))`")


def expand_braces(spec):
    """`a/{b,c}.ts` → ['a/b.ts', 'a/c.ts']；無花括號即原樣單元素。"""
    m = _RE_BRACE.match(spec)
    if not m:
        return [spec]
    head, body, tail = m.group(1), m.group(2), m.group(3)
    out = []
    for piece in body.split(","):
        out.extend(expand_braces(f"{head}{piece.strip()}{tail}"))
    return out


def parse_roster_row(text, track=TRACK_NAME, purpose=TRACK_PURPOSE):
    """自憲法全文抽出目標軌道列的**範圍欄**路徑集（brace 展開、去重排序）。

    找不到該列＝raise GateError（憲法被改名／該列被刪時 fail-loud，不得靜默回空集合——
    回空集合會讓 `G_a ⊆ G_c` 恆假之外的所有斷言失去意義，而空集合看起來像「沒東西要驗」）。
    """
    for line in text.splitlines():
        s = line.strip()
        if not s.startswith("|") or track not in s:
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if len(cells) < 3:
            continue
        if purpose not in cells[1]:
            continue
        paths = []
        for spec in _RE_PATH.findall(cells[2]):
            paths.extend(expand_braces(spec))
        if not paths:
            raise GateError(f"憲法 §III.2 之 {track}{purpose} 列找到了，但範圍欄抽不出任何檔案路徑"
                            f"——欄位形制被改過？")
        return tuple(sorted(set(paths)))
    raise GateError(f"憲法 §III.2 找不到軌道 {track} 的用途 {purpose} 那一列"
                    f"——軌道被改名／撤銷？本閘的授權來源即該列，找不到就不能假裝驗過")


# ── 產物檔頭掃描 ───────────────────────────────────────────────────────────────

def has_generated_header(path):
    """檔頭前 N 行含產物檔頭字樣（限檔頭——避免誤中散文裡提到該字樣的手寫檔）。"""
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for idx, line in enumerate(fh):
                if idx >= GENERATED_HEADER_MAX_LINE:
                    return False
                if GENERATED_HEADER in line:
                    return True
    except OSError:
        return False
    return False


def scan_generated(src_root):
    """`<base-web>/src/**` 底下帶產物檔頭的檔案（回相對 base-web 的 posix 路徑、排序）。"""
    out = []
    for dirpath, dirnames, filenames in os.walk(src_root):
        dirnames.sort()
        for name in sorted(filenames):
            full = os.path.join(dirpath, name)
            if has_generated_header(full):
                rel = os.path.relpath(full, os.path.dirname(src_root))
                out.append(rel.replace(os.sep, "/"))
    return tuple(sorted(out))


# ── 容器操作 ───────────────────────────────────────────────────────────────────

def _run(argv, stdin_bytes=None):
    return subprocess.run(argv, input=stdin_bytes, capture_output=True, cwd=REPO_ROOT)


def probe_container():
    """確認 dev stack 的 base-web 容器可用；不可用＝GateError（附啟動命令）。"""
    try:
        proc = _run(BASE_WEB_EXEC + ["sh", "-c", "test -d /app/node_modules/@elegant-router/vue"])
    except OSError as ex:
        raise GateError(f"無法執行 docker（{ex}）——本閘須在 dev stack 內跑外掛：{START_HINT}")
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout or b"").decode("utf-8", "replace").strip()
        raise GateError(f"base-web 容器不可用或缺 @elegant-router/vue（{detail or proc.returncode}）"
                        f"——請先啟動 dev stack：{START_HINT}")


def sh(script):
    """在 base-web 容器內跑一段 sh；非零即 GateError（帶原始輸出）。"""
    proc = _run(BASE_WEB_EXEC + ["sh", "-c", script])
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout or b"").decode("utf-8", "replace").strip()
        raise GateError(f"容器內命令失敗（rc={proc.returncode}）：{detail}")
    return proc.stdout.decode("utf-8", "replace")


def push_file(host_path, container_path):
    """host → 容器逐 byte 送檔（沙盒種子用）。"""
    with open(host_path, "rb") as fh:
        payload = fh.read()
    proc = _run(BASE_WEB_EXEC + ["sh", "-c", f"cat > '{container_path}'"], stdin_bytes=payload)
    if proc.returncode != 0:
        detail = (proc.stderr or b"").decode("utf-8", "replace").strip()
        raise GateError(f"送檔至容器失敗（{container_path}）：{detail}")


def make_sandbox(name):
    """建一顆乾淨沙盒：src/views、src/layouts、node_modules 皆 symlink 回 /app（唯讀取用）。"""
    box = f"{SANDBOX_ROOT}/{name}"
    sh(f"rm -rf '{box}' && mkdir -p '{box}/src' && "
       f"ln -s /app/src/views '{box}/src/views' && "
       f"ln -s /app/src/layouts '{box}/src/layouts' && "
       f"ln -s /app/node_modules '{box}/node_modules'")
    return box


def run_plugin(box):
    """在沙盒內跑一次外掛 → 回它實際寫出的檔案相對路徑（相對沙盒根，如 `src/…`）。"""
    runner = f"{box}/__gate-runner.mjs"
    proc = _run(BASE_WEB_EXEC + ["sh", "-c", f"cat > '{runner}'"],
                stdin_bytes=NODE_RUNNER.encode("utf-8"))
    if proc.returncode != 0:
        raise GateError("寫入沙盒 runner 失敗")
    proc = _run(BASE_WEB_EXEC + ["sh", "-c", f"cd '{box}' && node __gate-runner.mjs"])
    out = proc.stdout.decode("utf-8", "replace")
    err = proc.stderr.decode("utf-8", "replace")
    if proc.returncode != 0:
        raise GateError(f"沙盒內跑外掛失敗（rc={proc.returncode}）：{(err or out).strip()}")
    for line in out.splitlines():
        if line.startswith("__FILES__"):
            return tuple(sorted(json.loads(line[len("__FILES__"):])))
    raise GateError(f"沙盒 runner 未回報產出檔集：{out.strip()}｜{err.strip()}")


def _container_sh(script):
    """在 base-web 容器內跑一段 sh → `(rc, stdout)`；本閘 byte 比對的**生產執行面**。"""
    proc = _run(BASE_WEB_EXEC + ["sh", "-c", script])
    return proc.returncode, proc.stdout.decode("utf-8", "replace")


def _host_sh(script):
    """同形但跑在 host——★**僅 self-test 用**：讓比對邏輯能在暫存樹上實跑紅綠兩路，
    毋須 docker、毋須動 repo 內任何真檔。"""
    proc = subprocess.run(["sh", "-c", script], capture_output=True)
    return proc.returncode, proc.stdout.decode("utf-8", "replace")


def roster_verdict(produced, header_set, declared):
    """①產出檔集對賬的**判定核心** → `(檔頭集不符: bool, 憲法漏列: list)`。

    ★抽成一支函式的唯一理由：這兩道判定若在 `cmd_check` 與 self-test 各寫一份，改壞生產面
    那份時 self-test 走的是自己那份、照樣全綠（審查實暴的形）。生產面與 self-test C 一律
    呼叫本函式，改壞這裡兩邊同時紅。訊息組裝留在呼叫端——判定與措辭分離，措辭改動不會
    讓 self-test 需要跟著改。
    """
    return set(produced) != set(header_set), [p for p in produced if p not in declared]


def compare_against_worktree(box, rels, worktree_root="/app", exec_sh=_container_sh):
    """逐支比對沙盒產出 vs 版控；回不一致的 `[(rel, diff)]`。

    `worktree_root`／`exec_sh` **可注入**，預設即生產面（容器內 `/app`＝base-web worktree）。
    ★兩參數存在的唯一理由是讓 self-test F 段能實跑本函式本身：守門的紅路徑若沒被任何測試
    走過，它是否攔得住就純屬宣稱（ADR 0024 決定①）。生產呼叫端一律不帶這兩個參數。
    """
    bad = []
    for rel in rels:
        rc, _ = exec_sh(f"cmp -s '{worktree_root}/{rel}' '{box}/{rel}'")
        if rc != 0:
            _, diff = exec_sh(f"diff -u '{worktree_root}/{rel}' '{box}/{rel}' | head -40")
            bad.append((rel, diff))
    return bad


# ── check ─────────────────────────────────────────────────────────────────────

def cmd_check(constitution_path):
    self_test()

    # ①-a 憲法列的宣告集
    try:
        with open(constitution_path, encoding="utf-8") as fh:
            text = fh.read()
    except OSError as ex:
        raise GateError(f"讀不到憲法檔（{constitution_path}）：{ex}"
                        f"——授權來源缺席就不能假裝驗過") from ex
    declared = parse_roster_row(text)

    # ①-b 版控裡掛著產物檔頭的檔集
    header_set = scan_generated(os.path.join(REPO_ROOT, BASE_WEB_REL, "src"))

    probe_container()

    # ①-c 外掛實際產出檔集（空沙盒觀測——不預設任何清單）
    box_c = make_sandbox("observe")
    produced = run_plugin(box_c)

    if not produced:
        raise GateError("外掛在空沙盒零產出——外掛設定或 view 樹異常，本閘不能把「沒東西」當成綠")

    problems = []
    header_mismatch, missing = roster_verdict(produced, header_set, declared)
    if header_mismatch:
        problems.append(
            "① 產出檔集 ≠ 帶產物檔頭的版控檔集\n"
            f"    外掛實際產出：{list(produced)}\n"
            f"    版控帶檔頭者：{list(header_set)}\n"
            "    → 多出來的產出檔未進版控／版控多掛了檔頭；兩者必須一一對應")
    if missing:
        problems.append(
            "① 憲法 §III.2 第五列漏列產物檔（漏列一支＝該支完全無守）\n"
            f"    漏列：{missing}\n"
            f"    該列現有路徑：{list(declared)}\n"
            "    → 補進該列的範圍欄（走 §V.2 Amendment），或說明為何該支不受本軌道管")

    # ②重算冪等：種＝版控
    box_a = make_sandbox("idempotent")
    for rel in produced:
        sh(f"mkdir -p '{box_a}/{os.path.dirname(rel)}'")
        push_file(os.path.join(REPO_ROOT, BASE_WEB_REL, *rel.split("/")), f"{box_a}/{rel}")
    run_plugin(box_a)
    for rel, diff in compare_against_worktree(box_a, produced):
        problems.append(
            f"② 重算不冪等：{rel}\n"
            "    → 以版控現況為種重跑外掛後內容變了＝版控內容尚未收斂"
            "（新增／搬移 view 後忘了讓外掛重算、或重算結果沒 commit）\n"
            f"{diff}")

    # ③零手改：種＝上游基線
    baseline_root = os.path.join(REPO_ROOT, BASELINE_REL)
    if not os.path.isdir(baseline_root):
        print(f"[route-artifact-gate] ⤳ ③零手改斷言具名跳過：基線源倉 {BASELINE_REL}/ 缺席"
              f"（跑 bash tools/bootstrap.sh 建置後自動恢復）——★此時「手改產物檔」無人看管",
              file=sys.stderr)
    else:
        seeds_missing = [rel for rel in produced
                         if not os.path.isfile(os.path.join(baseline_root, *rel.split("/")))]
        if seeds_missing:
            raise GateError(f"基線源倉缺產物檔 {seeds_missing}——上游結構變動？"
                            f"③ 斷言的種子不完整就不能宣稱驗過")
        box_b = make_sandbox("no-hand-edit")
        for rel in produced:
            sh(f"mkdir -p '{box_b}/{os.path.dirname(rel)}'")
            push_file(os.path.join(baseline_root, *rel.split("/")), f"{box_b}/{rel}")
        run_plugin(box_b)
        for rel, diff in compare_against_worktree(box_b, produced):
            problems.append(
                f"③ 產物檔遭手改：{rel}\n"
                "    → 以**上游基線**為種重算的結果與版控不符；產物檔禁止手改"
                "（憲法 §III.2 第五列產物檔紀律），要改請改 view 樹或外掛設定後重算\n"
                f"{diff}")

    sh(f"rm -rf '{SANDBOX_ROOT}'")

    if problems:
        print("[route-artifact-gate] ✗ 路由產物四檔守門不通過：", file=sys.stderr)
        for p in problems:
            print("  " + p.replace("\n", "\n  "), file=sys.stderr)
        return 1

    print(f"[route-artifact-gate] ✓ 產出檔集 {len(produced)} 支對賬憲法第五列與產物檔頭；"
          f"重算冪等（種＝版控）與零手改（種＝基線）兩道皆 byte 相等（self-test 過）")
    return 0


# ── self-test（離線：純解析與集合判定，不需 docker／node）─────────────────────

FIXTURE_ROW = (
    "| **★BASE-WEB-MANAGE-PAGE-WIRING** | (i) IP 規則管理頁進場 | "
    "`src/locales/langs/{en-us,zh-cn}.ts`（各 1 塊）／`src/typings/app.d.ts`（1 塊）／"
    "`src/router/elegant/{imports,routes,transform}.ts`／`src/typings/elegant-router.d.ts`"
    "（後四支＝路由外掛產物、不標記） | 紀律敘述 |\n"
)

FIXTURE_TABLE = (
    "| 軌道 | 用途 | 範圍（檔案） | 紀律 |\n"
    "|---|---|---|---|\n"
    "| **★BASE-WEB-I18N-WIRING** | (ii) locale backend 樹 | `src/locales/langs/{en-us,zh-cn}.ts` | 別列 |\n"
    + FIXTURE_ROW
)

PRODUCED_FIXTURE = (
    "src/router/elegant/imports.ts",
    "src/router/elegant/routes.ts",
    "src/router/elegant/transform.ts",
    "src/typings/elegant-router.d.ts",
)


def self_test():
    """離線紅綠成對。失敗即 AssertionError（每次 check 連帶跑、防恆綠）。"""
    # A 花括號展開
    assert expand_braces("src/router/elegant/{imports,routes,transform}.ts") == [
        "src/router/elegant/imports.ts", "src/router/elegant/routes.ts",
        "src/router/elegant/transform.ts"], "self-test A：花括號群組展開錯"
    assert expand_braces("src/typings/app.d.ts") == ["src/typings/app.d.ts"], \
        "self-test A：無花括號應原樣"

    # B 正常列：抽得出七支（含三支非產物檔——`⊆` 上界的來源）
    declared = parse_roster_row(FIXTURE_TABLE)
    assert declared == tuple(sorted((
        "src/locales/langs/en-us.ts", "src/locales/langs/zh-cn.ts", "src/typings/app.d.ts",
        "src/router/elegant/imports.ts", "src/router/elegant/routes.ts",
        "src/router/elegant/transform.ts", "src/typings/elegant-router.d.ts"))), \
        f"self-test B：範圍欄路徑集抽錯，實得 {declared}"
    # ★「正常列不該有漏列」不在此另寫一份判定式——那是 C-1 的事，且由生產面同一支
    #   `roster_verdict` 判（判定式散成兩份，改壞生產面時 self-test 會照樣綠）。

    # C ★變異一：憲法該列**少列一支**產物檔 → 漏列偵測必紅。
    #   ★三小段一律呼叫**生產面同一支** `roster_verdict`——self-test 若另寫一份判定式，生產面
    #   那份被改壞時本段照樣全綠（等同沒測）。紅綠成對：C-1 正常列判綠、C-2 憲法漏列一支
    #   判紅、C-3 產出檔集與產物檔頭集不符判紅。
    verdict = roster_verdict(PRODUCED_FIXTURE, PRODUCED_FIXTURE, declared)
    assert verdict == (False, []), f"self-test C-1：正常列且檔頭集相符卻判紅（本閘會恆紅），實得 {verdict}"

    mut_declared = parse_roster_row(FIXTURE_TABLE.replace("／`src/typings/elegant-router.d.ts`", ""))
    verdict = roster_verdict(PRODUCED_FIXTURE, PRODUCED_FIXTURE, mut_declared)
    assert verdict == (False, ["src/typings/elegant-router.d.ts"]), \
        f"self-test C-2：憲法少列一支未被抓到（漏列＝該支完全無守），實得 {verdict}"

    verdict = roster_verdict(PRODUCED_FIXTURE, PRODUCED_FIXTURE[:-1], declared)
    assert verdict == (True, []), \
        f"self-test C-3：產出檔集 ≠ 帶產物檔頭的版控檔集未被抓到，實得 {verdict}"

    # D 目標列不存在（軌道被改名／撤銷）＝fail-loud，不得靜默回空集合
    for broken in (FIXTURE_TABLE.replace(TRACK_NAME, "SOME-OTHER-TRACK"),
                   FIXTURE_TABLE.replace("| (i) IP 規則管理頁進場 |", "| (ix) 別的用途 |")):
        try:
            parse_roster_row(broken)
        except GateError:
            pass
        else:  # pragma: no cover - 只有守門壞掉才會走到
            raise AssertionError("self-test D：目標列不存在時未 fail-loud")

    # E 範圍欄零路徑（欄位形制被改壞）＝fail-loud
    try:
        parse_roster_row(FIXTURE_TABLE.replace(
            "`src/locales/langs/{en-us,zh-cn}.ts`（各 1 塊）／`src/typings/app.d.ts`（1 塊）／"
            "`src/router/elegant/{imports,routes,transform}.ts`／`src/typings/elegant-router.d.ts`"
            "（後四支＝路由外掛產物、不標記）", "見下方散文"))
    except GateError:
        pass
    else:  # pragma: no cover
        raise AssertionError("self-test E：範圍欄零路徑時未 fail-loud")

    # F ★變異二：產物檔手改一行 → 第②③道的 byte 比對必紅。
    #   ★這裡**實跑生產函式 `compare_against_worktree`**（注入暫存工作樹根與 host sh 執行面），
    #   紅綠成對：先證兩側逐位相同時判綠（本閘不是恆紅品），再手改「工作樹側」一行——那正是
    #   「有人直接編輯產物檔、重算側不動」的形——證其判紅且 diff 指得出改了什麼。
    #   ★不寫成「另比一次 bytes」：那只斷言兩個建構即不同的字串不相等，守門整支失效也照過
    #   （ADR 0024 決定①所禁的 vacuous 形）。端到端形＝真跑第③道（種＝基線），見 cmd_check。
    with tempfile.TemporaryDirectory() as tmp:
        worktree = os.path.join(tmp, "worktree")
        box = os.path.join(tmp, "box")
        rel = "src/typings/elegant-router.d.ts"
        body = ("// Generated by elegant-router\n"
                "export type RouteKey = 'manage_ip-rule' | 'manage_role';\n")
        for root in (worktree, box):
            os.makedirs(os.path.join(root, os.path.dirname(rel)))
            with open(os.path.join(root, rel), "w", encoding="utf-8") as fh:
                fh.write(body)
        assert compare_against_worktree(box, (rel,), worktree, _host_sh) == [], \
            "self-test F：兩側逐位相同卻報不一致——本閘會恆紅，等同無用"

        with open(os.path.join(worktree, rel), "w", encoding="utf-8") as fh:
            fh.write(body.replace("'manage_ip-rule'", "'manage_ipRule'"))
        bad = compare_against_worktree(box, (rel,), worktree, _host_sh)
        assert [r for r, _ in bad] == [rel], \
            f"self-test F：產物檔手改一行未被抓到（第②③道等同不存在），實得 {bad}"
        assert "manage_ipRule" in bad[0][1], \
            f"self-test F：判紅了但 diff 指不出改動內容（報紅無從追查），實得 {bad[0][1]!r}"

        # G 產物檔頭辨識：限檔頭 N 行內、且散文提及不算
        assert has_generated_header(os.path.join(box, rel)), "self-test G：檔頭第 1 行有字樣卻判否"
        late = os.path.join(tmp, "late.ts")
        with open(late, "w", encoding="utf-8") as fh:
            fh.write("\n" * GENERATED_HEADER_MAX_LINE + f"// {GENERATED_HEADER}\n")
        assert not has_generated_header(late), "self-test G：檔頭窗外的字樣不該算產物檔"


def main(argv):
    args = argv[1:]
    constitution = os.path.join(REPO_ROOT, CONSTITUTION_REL)
    if "--constitution" in args:
        idx = args.index("--constitution")
        if idx + 1 >= len(args):
            print("--constitution 需帶路徑", file=sys.stderr)
            return 64
        constitution = args[idx + 1]
        del args[idx:idx + 2]
    cmd = args[0] if args else "check"
    if cmd == "test":
        self_test()
        print("[route-artifact-gate] ✓ self-test 過（花括號展開／列定位／"
              "★憲法少列一支必紅＋產物檔頭集不符必紅〔實跑 roster_verdict、相符時判綠成對〕／"
              "目標列缺席 fail-loud／範圍欄零路徑 fail-loud／"
              "★產物檔手改一行必紅〔實跑 compare_against_worktree、相同時判綠成對〕／檔頭窗）")
        return 0
    if cmd != "check":
        print(f"用法：{argv[0]} [check|test] [--constitution <path>]", file=sys.stderr)
        return 64
    try:
        return cmd_check(constitution)
    except GateError as ex:
        print(f"[route-artifact-gate] ✗ 環境／前提不成立：{ex}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
